### ISSUE TITLE
"O" command doesn't open line above cursor in Editor mode, it behaves like "o" command itself.

### ISSUE THREAD

**Issue by lifecontd** [pit-ray/win-vind#1]
This is nice tool. I've been looking for something like this for some time now, I really like the Editor mode that you've implemented. My main usecase that I want to get working is using this inside MS Outlook.
"O" command doesn't open line above cursor in Editor mode, it behaves like "o" command only.
I'm using Windows 10. And trying this out in Notepad.

**Comment by pit-ray** [comment]
Thank you for using and reporting.  

`Editor Mode` is a prototype function, so some commands are not implemented or have some bugs. 

I added new functions as follows.
- Insert BOL (I/gI)
- Append EOL (A)
- Begin New Line Above Caret (O)

Please try it.
|Type|URL|
|---|---|
|Installer|<a href="https://github.com/pit-ray/win-vind/blob/master/bin/setup_win-vind_1.2.0_beta.exe">Download</a>|
|Zip|<a href="https://github.com/pit-ray/win-vind/tree/master/bin/win-vind">Download</a>|
<br>
