### ISSUE TITLE
[Question] Use EasyClick Only

### ISSUE THREAD

**Issue by atomdmac** [pit-ray/win-vind#10]
**Question**
Is there a way to configure `win-vind` such that it _only_ listens for the triggers for EasyClick/"EasyMotion-like Hints" but passes all other keybinds through to the OS?  Basically, I'd like to disable all other functions and modes and _just_ use the EasyClick feature.

So far, I've tried removing all entries from `keybinds.json` besides the ones for `EasyClick` but that effectively blocks all normal keyboard input.

**Comment by atomdmac** [comment]
Right after posting this, I figured it out:

* Remove all non-`EasyClick` from the default `keybinds.json`
* The default `EasyClick` binds are added to `GUI NORMAL` mode / `guin`.  Either remove them or move them to `guii`
* Either use the `win-vind` GUI or edit `settings.json` directly to make the default mode be `GUI INSERT`

**Comment by pit-ray** [comment]
Thank you for using it.

`GUI Insert` has **only** `change_to_normal` that change mode to `GUI Normal` in default and passes all inputs to OS. Therefore, you can use only `EasyClick` in the following steps.

1. Make the initial mode to `GUI Insert`.
2. Set bindings of `easy_click_***` in `GUI Insert` (`guii`). 

Example: (`Ctrl` + `Shift` + `f`)
```json
    {
        "name": "easy_click_left",
        "guin": ["FF", "Fo"],
        "guii": ["<ctrl-F>"],   <----- THIS
        "guiv": [],
        "edin": [],
        "edii": [],
        "ediv": [],
        "edivl": [],
        "cmd": ["ecl"],
        "mycwn": [],
        "mycwi": [],
        "en": "EasyClick (Left Click)",
        "ja": "EasyClick (左クリック)"
    },
```

You can refer to keywords in <a href="https://pit-ray.github.io/win-vind/cheat_sheet/keyword_lists/">Keyword List - win-vind</a>. 

If you want to disable `change_to_normal` (`<Esc-Left>`, etc.), set an empty string to its `guii`.
```json
Example:
    {
        "name": "change_to_normal",
        "guin": ["<Esc-Left>", "<Esc-Right>", "<Esc-Up>", "<Esc-Down>", "<F9>"],
        "guii": [""],    <----- THIS
        "guiv": ["<guin>"],
        "edin": ["<guin>"],
        "edii": ["<guin>"],
        "ediv": ["<guin>"],
        "edivl": ["<guin>"],
        "cmd": [],
        "mycwn": ["<guin>"],
        "mycwi": [],
        "en": "GUI Normal Mode",
        "ja": "GUI ノーマルモード"
    },
```

The next version improves the performance of `EasyClick` and adds a preset feature. Please look forward to it.

**Comment by az-pz** [comment]
If someone wants to do it now using `.vindrc`, they can use this:
```
set initmode guii
imap <ctrl-f> <easy_click_left>
```
