### ISSUE TITLE
[Question] way to make the cmd label disappear?

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#106]
Hi,

I have the following in my `.vind-rc`:
```
set cmd_fadeout=3600
```
-- which works very well for me, as it always shows me the current mode. However, there are specific situations when this label hide an important detail (even though I am using a small fontsize). It would be nice if there was a way to hide/make visible the current cmd, and then I could map that to a specific key, so it would be easy to toggle the visibility of the labels.

thanks for your consideration!

**Comment by pit-ray** [comment]
Simply use the macro for switching.

```vim
" 5 seconds
gnnoremap <ctrl-4> :set cmd_fadeout=5<cr>

" 1 hour
gnnoremap <ctrl-5> :set cmd_fadeout=3600<cr>
```

Thanks.

**Comment by gilbh** [comment]
Thank you.

It works very well in most situations, but when i try to make this in RESIDENT, the key is not activated (RESIDENT is usually the mode in which this feature is most important).

**Comment by pit-ray** [comment]
To achieve in RESIDENT, you should define a map for RESIDENT mode transition and add such macros I mentioned above.

e.g.

```vim
rnoremap <ctrl-alt-5> to_command
rnoremap <ctrl-4> <ctrl-alt-5>set cmd_fadeout=5<cr>
```

Ideally, it can automatically run this command when it enter RESIDENT, so `audocmd` is crucial for us.

Thanks.

**Comment by gilbh** [comment]
The above solution works.

Yes, I think the `autocmd` is a brilliant solution. This has not been rolled out yet, correct?

**Comment by pit-ray** [comment]
I'm implementing in opened pull requests now. However, to implement autocmd, redesigning of the core system is needed, so I am re-thinking win-vind's core now. Probably, it does not finish immediately.

When I finished this, I'll publish the new version anyway.

thanks.
