### ISSUE TITLE
Not detecting VS Code

### ISSUE THREAD

**Issue by ameeruljunaidi** [pit-ray/win-vind#11]
Hi,

For some reson it's not detecting VS Code.

For example, when I try to select the window using <C-w><h> or <C-w><l>, the cursor is not jumping to the window.

EasyClick also does not work.

I am using VS Code Insiders (but it didn't work for normal VS Code either) on a Window 10 x64 machine.

**Comment by pit-ray** [comment]
Thank you for using it.
It may be undiscovered bugs, so I want more details. 

Let me know what key-bindings do not work (e.g. `gg`, `t`). 
And, please check log files in `~/.win-vind/log/` after its behavior.

By the way, in my test environment, EasyClick works in VS Code.  

![vscode](https://user-images.githubusercontent.com/42631247/112414657-c28a7800-8d65-11eb-88c9-3f134daa4822.jpg)
VSCode: 1.54.3 (Stable), 1.55.0 (Insiders)
Windows 10: Home 64bit 20H2 Build 19032.867

**Comment by ameeruljunaidi** [comment]
Hi, I'm not entirely sure what happened, but I restarted win-vind and it now works, thank!

**Comment by fdawans** [comment]
Thank you for your software.
I have been looking for such a thing for a while but there was nothing satisfying on Windows.

EasyClick does not work for me in VSCode 1.58.2 , I am using win-wind 4.0.1 and Windows 10 Enterprise 10.0.17134.
I only see a 'D' in the middle of the screen.

**Comment by fdawans** [comment]
Thank you for your software.
I have been looking for such a thing for a while but there was nothing satisfying on Windows.

EasyClick does not work for me in VSCode 1.58.2 , I am using win-wind 4.0.1 and Windows 10 Enterprise 10.0.17134.
I only see a 'D' in the middle of the screen.

**Comment by pit-ray** [comment]
> I only see a 'D' in the middle of the screen.

Hi.
Thanks for using win-vind.
Maybe once you click on the area inside the window, a hint should appear. We are currently redesigning the implementation of this factor. Please wait for a while.

**Comment by fdawans** [comment]
Thank you for the feedback.
If I click inside, it is also not working.
I will already learn to use it in all the other apps and wait for the new version, good luck!

**Comment by pit-ray** [comment]
Hi.
I have just published the [pre-release](https://github.com/pit-ray/win-vind/releases/tag/v4.1.0-rc1). Please try it and let me know if you have the same problem.
Thanks.

**Comment by pit-ray** [comment]
Today, I tried Windows 10 1803 x64 and was able to reproduce the same issue.

Since it works fine on the latest Windows 10 and Windows 11, it may be due to minor differences in Windows API. Until I know more about the cause, we will specify it as an issue in the README.

Thanks.
