### ISSUE TITLE
[Bug] keystroke state will stuck when mapping a modifier key in insert mode

### ISSUE THREAD

**Issue by SunnyLimc** [pit-ray/win-vind#111]
# About Bug
As stated in title, any key mapping from insert mode will first cause **key reproduce to currently focused application** AND **call win-vind function** simultaneously.

Based on the above, if I noremap a normal key such as <tab-[> to edi-mode, the TAB key will be triggered simultaneously when I want to enter edi-mode.

Back to what this title says, if I map a modifier key such as <ralt-[> to edi-mode, the ralt key state will NOT be released when I back to insert mode.

PS: ESC and Function keys are too far away from my hand to press.

# Steps to reproduce
1. configure mappings
2. press shortcut
3. go back to insert mode
4. press any single key like A-Z (do not press modifier key) and you will be aware that the modifier key is pressed.

# Environments

|Environments|Delete the example and fill in your information.|
|:---:|:---|
|Windows Edition|[e.g. 11 Enterprise]|
|Windows Version|[e.g. 21H2]|
|Windows Build|[e.g. 22000.832]|
|Architecture|[e.g. 64bit]|
|win-vind Version|[e.g. 4.3.3]|
|win-vind Install Type|[installer]|

**Comment by pit-ray** [comment]
Is it the same as #40?
https://github.com/pit-ray/win-vind/issues/40#issuecomment-1100882222

The ralt is a special key, so does not do normal behavior. Probably, API causes this issues.

Thanks.
