### ISSUE TITLE
[Question] It's slow to trigger win-vind function from Command-line

### ISSUE THREAD

**Issue by SunnyLimc** [pit-ray/win-vind#112]
Because of #111，I try another ways to map functions from insert mode as [the link](https://gist.github.com/pit-ray/267a89b596dce566a8ae9c9ff9a8057f) described with Autohotkey.

But functions called from command line have a large delay (approximately 0.5s - 1s instead of instantly) which is inconvenient for daily using such as switch mode.

**Comment by pit-ray** [comment]
That's right.
The the interval time of synchronous timer is hard-coded. 

https://github.com/pit-ray/win-vind/blob/12ea669c77d62f0b30d677f9de66229d1421287c/src/core/entry.cpp#L113

In this implementation, the main process read the function name periodically in the shared memoris and the sub process write the function name passed by --func.

I would like to improve this behavior in the next version.

If you have any solutions, please let me know.

Thanks.
