### ISSUE TITLE
[Question] How to map 'Find Text` in Word from EDIT_NORMAL?

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#113]
Hi,

I am trying to do this:
```
ennoremap / to_insert<ctrl-f>
```

-- so when I clickc on `/` in EDIT_NORMAL inside Microsoft Word I will get the Find Text window. But running the above only switched to INSERT and enters a new line.

How to do this?

Thanks!

**Comment by pit-ray** [comment]
The latest version doesn't have the directly way to call the function in a definition of a macro.

Now, I'm implementing the way in #109 from discussion in #96 and #104.

In the latest version, you can use the following solution.

```
ennoremap <f19> to_insert
enmap / <f19><ctrl-f>
```

To pass the key message into Windows, we need to use `map` command. However, we don't desire the key stroke, for changing the mode to insert mode, is passed to Windows, so instead use <f19> key.

Thanks.

**Comment by gilbh** [comment]
Oh yeah! It works great now! Thanks!
