### ISSUE TITLE
[Feature] Add a mouse fast movement mode (similar to easymotion)

### ISSUE THREAD

**Issue by photkey** [pit-ray/win-vind#115]
When starting this mode, cut the screen into 676 areas (26*26=676) as in the picture below, assign each area to a combination of two letters, when pressing these two letters, the mouse moves to the center of the corresponding area (similar to easymotion); then automatically switch to slow mouse movement mode, because only a small range of movement is needed, this time need to improve the precision of movement.
![145061639-8fb9104f-18f3-43fc-a38d-9aed5ce90096](https://user-images.githubusercontent.com/60434581/182124471-e19fe807-2325-4256-bd36-ed9882c94960.png)
PS: the first 25 lines I am a direct copy of the same content, can not really hand knock 676 groups of letter combinations ...... meaning should be able to see . This figure may look like the first feeling is more chaotic, full of letters; the actual use, when pressing the shortcut key at the same time, the eyes only need to focus on the mouse to go to that location, other locations simply do not need to see.

Advantages: no matter how far away, only two letter keys can be precisely positioned to the designated location of the screen 1/676, in many cases no longer need to move the mouse, direct click can be; even if you still need to move is also a small range of precise movement (the mouse moved in the center of a small grid position, only need to move within a small grid of 1/4 range)

Possible additional configurations: mouse movement speed after pressing two navigation letters, keys to switch movement speed (fast/slow), keys to quickly enter easymotion mode in mouse mode
In addition, the location of the 676 center points should not need to be calculated every time you start up. The first time you start up, calculate once, and then cache these positions with the corresponding letters, which should speed up the startup.

**Comment by imshenwei** [comment]
bravo!!! completely what i am thinking bout!!! very exciting if this is made.

**Comment by imshenwei** [comment]
https://github.com/pit-ray/win-vind/issues/99

**Comment by pit-ray** [comment]
I added this task into https://github.com/users/pit-ray/projects/2.

**Comment by pit-ray** [comment]
@photkey @imshenwei @qaptoR 
Today, I released v5.1.0-beta including this feature. Please try it.
https://github.com/pit-ray/win-vind/discussions/155#discussioncomment-5766623
