### ISSUE TITLE
About the picture in the tutorial

### ISSUE THREAD

**Issue by xp12047** [pit-ray/win-vind#119]
**Select based on the displayed letters**      

   Is the letter prompt selection in the picture the prompt of the ALT key in the win system?  Is there a key in vim mode to do this?  
Thanks!  I like your project。
![image](https://user-images.githubusercontent.com/56335408/186914592-83f65c89-8b46-4ac3-b4f2-db51cc6d53bd.png)

**Comment by pit-ray** [comment]
Is it about EasyClick? It is MS Office's Alt-like feature for every application.

If you want to call this function in editor normal mode, try `ennoremap`.

```vim
ennoremap FF easy_click_left
```

Thanks.

**Comment by xp12047** [comment]
> 是关于 EasyClick 的吗？它是适用于每个应用程序的 MS Office 的类似 Alt 的功能。
> 
> 如果要在编辑器正常模式下调用此函数，请尝试`ennoremap`.
> 
> ```viml
> ennoremap FF easy_click_left
> ```
> 
> 谢谢。

yes thank you very much

**Comment by xp12047** [comment]
> > 是关于 EasyClick 的吗？它适用于每个应用程序的 MS Office 的类似 Alt 的功能。
> > 如果在编辑器正常模式下要调用此函数，请尝试`ennoremap`。
> > ```viml
> > ennoremap FF easy_click_left
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 谢谢。
> 
> 是的谢谢你

Just found a weird problem and I want to record this magical moment with obs.  But after recording, there are no letter prompts in the video?

**Comment by xp12047** [comment]
> > > 是关于 EasyClick 的吗？它适用于每个应用程序的 MS Office 的类似 Alt 的功能。
> > > 如果在编辑器正常模式下要调用此函数，请试用`ennoremap`。
> > > ```viml
> > > ennoremap FF easy_click_left
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 谢谢。
> > 
> > 
> > 是的谢谢你
> 
> 刚刚发现一个奇怪的问题，想用obs记录下这个神奇的时刻。但是录制后，视频中没有字母提示？

solved.  Changed recording software
