### ISSUE TITLE
[Bug] `to_resident` behaves like `to_insert`

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#121]
Hi,

When I try this in `.vindrc`:
```
ennoremap <ctrl-6> :set cmd_fadeout=5<cr>to_resident
```

Vind switches to INSERT and not to RESIDENT.

Thanks!

**Comment by pit-ray** [comment]
If you map `<esc-down>` to to_resident, please use the mapping.

Like this.
```
ennoremap <ctrl-6> :set cmd_fadeout=5<cr><esc-down>
```
Thanks.

**Comment by pit-ray** [comment]
The direct mapping, which use function name in macro, is not supported yet, as mentioned in https://github.com/pit-ray/win-vind/issues/113#issuecomment-1264611594.
