### ISSUE TITLE
[Question] How can I use Windows built-in shortcuts

### ISSUE THREAD

**Issue by happyTonakai** [pit-ray/win-vind#123]
How can I use keyboard shortcuts in Windows in GUI normal mode?

Such as `ctrl-w` to close active window, `alt-d` to select the directory bar, and other default hotkeys in some softwares such as `ctrl+t` to open a new tab in Chrome/Edge.

What I need is to keep some commands' orignal functionality. What I tried is to use `gnunmap` to remove the mapping and map these hotkeys to themselves, like
```
gnunmap <ctrl-w>
gnnoremap <ctrl-w> <ctrl-w>
```
But that doesn't work. To make sure this is not related to the window binding of `<C-w>`, I also tried `ctrl-t` which also fails.

Can I achieve this goal? Thank you.

**Comment by pit-ray** [comment]
The self-mapping to pass key messages to Windows is considered, as mentioned in https://github.com/pit-ray/win-vind/issues/55#issuecomment-1006879439.

In v4.3.3, please use [pre-defined functions ](https://pit-ray.github.io/win-vind/cheat_sheet/functions/#tab)as following.
```
gnnoremap <ctrl-w> close_current_window
gnnoremap <ctrl-t> open_new_tab
```

Thanks.

**Comment by pit-ray** [comment]
This self-mapping feature is including in v5.0.0.
