### ISSUE TITLE
Changing the easyclick command from FF to f 

### ISSUE THREAD

**Issue by kenshinohta** [pit-ray/win-vind#13]
**Describe the feature you'd like**

[English] I was trying to change the key bindings of the easyclick command from <shift>ff to just f, but the change does not get reflected after modifying the setting. Is this a bug, or am I missing something? 

[Japanese] Win Vind を使わせていただいてありがとうございます。非常に気に入っております。一つ疑問なのですがKey Bindings を使ってeasyclick のコマンドをFF から fに変えたいのですが変更が反映されません。これはバグでしょうか？

**Comment by pit-ray** [comment]
ご利用いただきありがとうございます。

ご指摘いただいた点を確認したところ、
- GUIの検索後のリストによる変更が、検索前のリストに対して行われる問題
- JSONを書き換えても再起動するまで反映されない問題

がありました。これらのバグですが、バージョン3.2.3としてパッチを当てましたので、アップデートしてお試しください。

[github.com/release/tag/v3.2.3](https://github.com/pit-ray/win-vind/releases/tag/v3.2.3)

ただ、それだけでなく、`f`キーが他の機能にすでにバインドされていることも絡んでいるようです。その機能の識別子は、`jump_to_any`で、<a href="https://pit-ray.github.io/win-vind/cheat_sheet/mouse_ctrl/#jump-cursor-by-keyboard-mapping">キーボードマッピングによるカーソル移動の機能</a>です。したがって、`jump_to_any`のバインディング`f`の削除もあわせて行ってください。

現在のwin-vindは、カスタマイズという点において非常に使いにくいと思いますが、次のアップデートで大幅に改善する予定です。

最後に、このIssuesのタイトルが**内容の文**になっているため、現在のタイトルを**Describe the feture you'd like** ...から始まる本文に移動させ、タイトルを簡単な要約にしていただけませんか。お手数おかけしますが、よろしくお願いいたします。

**Comment by kenshinohta** [comment]
丁寧なご返信誠にありがとうございます。

先ほどjump_to_anyのコマンドを調整したところf key で使えるようになりました。これでかなりコマンドタイピングがスムーズになるとおもいます。

GUIの検索のリスト変更が反映されない点についても、改善されているのが確認できました。

重ねて迅速な対応誠にありがとうございます。

次のアップデートを楽しみにしてお待ちしております！
