### ISSUE TITLE
[Bug] MultiMonitor Issue with GUI Normal

### ISSUE THREAD

**Issue by aus10code** [pit-ray/win-vind#130]
# About Bug
On my 2nd and 3rd monitor, the text tags don't popup in the correct positions when doing FF. When I enter the letter binding the mouse goes to the correct control of where the text should be. Only the display of the text appears to be incorrect.

For example. If I hit the binding S as show in the GIF, it will correctly click the File menu button

# GIF
![multiMonitorIssue](https://user-images.githubusercontent.com/62197117/202300012-35dbf965-1b04-4b4d-b5ed-143c8c280f69.gif)

# Environments
|Windows Edition| 11 Pro]
|Windows Version| 22H2
|Windows Build| 22621.674
|Architecture| 64bit
|win-vind Version| 4.3.3
|win-vind Install Type| winget

**Comment by pit-ray** [comment]
Thank you for using it.

Perhaps it may be related to Per-Monitor V2. Building the commit of the pull request merged in #85, #54 may solve the problem.

The official release that incorporates this commit will be v5.0 beta. The v5.0-beta is testing in Discussion now.

If needed, I will attach the built binaries of #85.

**Comment by aus10code** [comment]
sure, I can try out the binaries from [#85](https://github.com/pit-ray/win-vind/pull/85). I don't know what that entails so you may have to guide me after you provide the binaries.

**Comment by pit-ray** [comment]
I built #85, please try it.
[win-vind_build-85_64bit_installer.zip](https://github.com/pit-ray/win-vind/files/10032788/win-vind_build-85_64bit_installer.zip)
[win-vind_build-85_64bit_portable.zip](https://github.com/pit-ray/win-vind/files/10032789/win-vind_build-85_64bit_portable.zip)

**Comment by aus10code** [comment]
That fixed it! Thanks for building the installer for me!
