### ISSUE TITLE
[Question] A Question about Screenshoot

### ISSUE THREAD

**Issue by dp0qb** [pit-ray/win-vind#133]
Hi, thanks for your great work. But it doesn't seem work well when I was trying to capture a screenshoot by other tools, for example Snipaste. Only in the resident mode I can start  up the screenshoot window, but I can't drag or move my cursor in that case. I wonder how to capture a screenshoot. Thanks a lot.

**Comment by pit-ray** [comment]
Thanks for using it.

As noted in the [usage document](https://pit-ray.github.io/win-vind/usage/), the modes except for Insert and Resident block the key messages to other applications. 

And the insert/resident mode does not have any mouse moving function by [default](https://pit-ray.github.io/win-vind/cheat_sheet/defaults/), but you can customize them.

Thanks.
