### ISSUE TITLE
The latest version v5.0.0-beta2 installed

### ISSUE THREAD

**Issue by xp12047** [pit-ray/win-vind#135]
The latest v5.0.0-beta2 version installation needs to uninstall the old version first.  Otherwise the installation will fail.  After the installation is complete, it is still version 5.0.0.  Will there be a new version later that can be installed directly without uninstalling?

**Comment by pit-ray** [comment]
Please use portable version for test. The portable version is entirely within the unzipped directory and is isolated from the system.
However, since only one win-vind can be started, the old win-vind installed on the system should be temporarily terminated during the test.

Thanks.

**Comment by gilbh** [comment]
Okay. I will switch to the portable

**Comment by xp12047** [comment]
> 请使用便携版进行测试。便携版完全在解压后的目录中，与系统隔离。 不过由于只能启动一个win-vind，所以测试时应该暂时终止系统上安装的旧win-vind。
> 
> 谢谢。

ok，thanks
