### ISSUE TITLE
[Feature] window swtiching, choose by shortcut like easy-motion

### ISSUE THREAD

**Issue by postcypunk** [pit-ray/win-vind#138]
when using <C-w> s add keyborad shortcut like easy motion
if i use  EasyClick when task swtiching, it only shows the close button ,not the actual window

**Comment by pit-ray** [comment]
@postcypunk 
Sorry for my late reply.

That's good idea.
The future swich_window should supports hinting switching.

I added win-vind projects.
ref. https://github.com/users/pit-ray/projects/2

Thanks.

**Comment by pit-ray** [comment]
This feature is supported in v5.5.0.
