### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#14]
Love Win-Vind!

Is it possible to start the program in GUI Insert instead of GUI Normal? This way the uninitiated will not think the keyboard stopped working after each restart....

Thanks.

**Comment by pit-ray** [comment]
Thank you for using it!

Yes. Please set **GUI Insert** at **Preferences/settings/Initial Mode**.

![initmode](https://user-images.githubusercontent.com/42631247/113421839-b443f800-9406-11eb-9c32-df9f4dfd66f8.jpg)

**Comment by gilbh** [comment]
Fantastic!
