### ISSUE TITLE
Hello, help with the memo sheet

### ISSUE THREAD

**Issue by xp12047** [pit-ray/win-vind#143]
Sorry. I don't know how to press the keys.  
![Screenshot_20230211_103544](https://user-images.githubusercontent.com/56335408/218234748-e3c02899-a91c-40c5-b9bb-747a984e9d64.jpg)     
Inside the default mapping. For example, the first one in the figure.``` <C-w>+```     
I am holding down the ctrl on the keyboard and then press the w letter Jian finally then press the + key? It doesn't seem to work.  
thanks

**Comment by pit-ray** [comment]
Thanks for using it.

`<C-w>` means <kbd>Ctrl</kbd> and <kbd>w</kbd> press at the same time. Therefore, `<C-w>+` means <kbd>Ctrl</kbd> and <kbd>w</kbd>, then release them, and then press <kbd>+</kbd>. By the way, `+` requires a shift key according to your keyboard layout.

Also, don't forget that the binding depends on the current mode

**Comment by xp12047** [comment]
> 感谢您使用它。
> 
> `<C-w>`表示Ctrl并w同时按下。因此，`<C-w>+`意味着Ctrl和w，然后松开它们，然后按下+。顺便说一下，`+`根据您的键盘布局需要一个 shift 键。
> 
> 另外，不要忘记绑定取决于当前模式

thanks :smiley_cat:
