### ISSUE TITLE
[Bug] command `<to_edi_normal>` moves the caret focus to upper menu box

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#147]
# About Bug
In Word (when Ribbon is visible by default), when I switch `<to_edi_normal>` (doesn't matter which key combination), the caret focus object jumps from the document to the Font Size box (Home->Font Size). Similarly, in FireFox, the same action will shift the caret focus object from the webpage to the address bar. (So same problem).

This happened in previous versions, but right now I am using v5.0.0.5, and it also happens.

Edition	Windows 10 Pro
Version	21H2
Installed on	‎3/‎13/‎2021
OS build	19044.2728
Experience	Windows Feature Experience Pack 120.2212.4190.0

Thank you!

**Comment by gilbh** [comment]
Hi

I was wondering if this issue is considered.

Thanks!

**Comment by pit-ray** [comment]
I assume this is due to the `autofocus_textarea` option being enabled.
Please try `set noautofocus_textarea`.

**Comment by gilbh** [comment]
Indeed, this seems to have been resolved. Thanks so much!!
