### ISSUE TITLE
[Feature] Project name `Vind`?

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#148]
Hi all,

Does it make sense to shorten the project name from `win-vind` to just `vind`? I think it sounds much better, and brands the project better.

Just a thought.

Best!

**Comment by pit-ray** [comment]
If we want to name it `vind`, we will start it in a separate repository as a cross-platform after we have accumulated more technical knowledge.
I don't think win-vind has achieved comfortable operation yet.

**Comment by gilbh** [comment]
Thanks!

I appreciate the forward-looking thinking.

Best
