### ISSUE TITLE
[Bug] long delay before entering `<to_edi_normal>` using `map`

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#149]
# About Bug
I switch to `normal` using the the <ins> key. Here's the mapping in `.vindrc` when in INSERT more:
```
inoremap <insert> <to_edi_normal>
```

-- but the response time is very slow, about 1sec. 

When I do the opposite operation:
```
ennoremap <esc> <to_resident>
```
 
-- the response time is very fast.

Any reason for the difference and how to fix this?

This is in vind v5.0.0.5

Thanks!!

# Environments
Edition	Windows 10 Pro
Version	21H2
Installed on	‎3/‎13/‎2021
OS build	19044.2728
Experience	Windows Feature Experience Pack 120.2212.4190.0

**Comment by pit-ray** [comment]
@gilbh 
Perhaps it is the `autofocus_textarea` option. When this option is enabled, the input area near the mouse is automatically focused after UI scanning when entering Edi Normal.
If you want to use this feature without any delays, consider using uiacachebuild.

**Comment by gilbh** [comment]
I think this solved it. Thanks!
