### ISSUE TITLE
[Question] Jumping from one mode to another

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#15]
Is there a way to jump directly from GUI Insert to Editor Insert (i.e., without going first "up" to GUI Normal and then "down" twice? 

![image](https://user-images.githubusercontent.com/39532610/113426418-6f39aa80-93a1-11eb-9642-224644649ff2.png)

Thanks!

**Comment by pit-ray** [comment]
Yes.
This model describes just the default, so you can customize the layer.

All mode state transitions exist as functions and each function has bindings in each mode. <a href="https://pit-ray.github.io/win-vind/cheat_sheet/mode_ctrl/">Cheat Sheet/Mode Control</a>

**Method**
- Use GUI
1. Show Preferences/Bindings.
1. Search change_to_edi_insert and push `Edit With Vim`

- Use your editors
1. Open `~/.win-vind/bindings.json` with your editor.
1. If you use Vim, search the line by `/change_to_edi_insert`.

Then, you can see it.
```json
    {
        "name": "change_to_edi_insert",
        "guin": [],
        "guii": [],
        "guiv": [],
        "edin": ["i"],
        "edii": [],
        "ediv": [],
        "edivl": [],
        "cmd": [],
        "mycwn": [],
        "mycwi": [],
        "en": "Insert before a caret (Vim Emulation: i)",
        "ja": "キャレットの前に挿入 (Vimエミュレーション: i)"
    },
```

"`edin`": ["`i`"], means,
"`If the current mode is this`": ["`the function is called by this bindings`"]

Thus, if you want to call `change_to_edi_insert` in **GUI Insert** with `<alt-i>`.
```json
    {
        "name": "change_to_edi_insert",
        "guin": [],
        "guii": ["<alt-i>"],  <====
        "guiv": [],
        "edin": ["i"],
        "edii": [],
        "ediv": [],
        "edivl": [],
        "cmd": [],
        "mycwn": [],
        "mycwi": [],
        "en": "Insert before a caret (Vim Emulation: i)",
        "ja": "キャレットの前に挿入 (Vimエミュレーション: i)"
    },
```

And, you can refer to the keywords in <a href="https://pit-ray.github.io/win-vind/cheat_sheet/keyword_lists/">Cheat Sheet/Keyword List</a>

However, the customizability of win-vind in the latest release is so bad. Therefore, I am redesigning it by overwriting-style like `.vimrc`. Please look forward to the next version.

**Comment by gilbh** [comment]
Thanks! This is helpful!
