### ISSUE TITLE
The character '~' is invalid ascii key. Could not initialize win-vind, so terminate. (Windows Error Code: 0)

### ISSUE THREAD

**Issue by kvgelder** [pit-ray/win-vind#151]
Tried both the portable x64 version, and the winget get version.

I suspect this is a similar issue to: https://github.com/pit-ray/win-vind/issues/53
Except I use a (slighty modified) dvorak layout. The tilde button creates the following characters:
normal: §
Shift key: ½

Edit
Selecting a traditional QWERTY US keyboard layout, does indeed resolve the issue. It seems I can swap back to my DVORAK layout after the application has loaded, though.

Error message:

`An runtime exception occured from class std::unordered_set<class vind::core::KeyCode,struct std::hash<class vind::core::KeyCode>,struct std::equal_to<class vind::core::KeyCode>,class std::allocator<class vind::core::KeyCode> > __cdecl vind::core::parse_ascii_command(char). The character '~' is invalid ascii key code. Could not initialize win-vind, so terminate. (Windows Error Code: 0)`

Environment (please complete the following information):

Windows 11
OS Type: 64bit
OS Version: 22H2
OS Build: 22621.1413
win-vind Version: 5.0.0
win-vind Type: winget and portable
Is it reproducible?: Yes

**Comment by pit-ray** [comment]
How can I reproduce it?
Can I reproduce it by installing US Dvorak on Windows?

**Comment by kvgelder** [comment]
My apologies, I originally thought it had to do with the tilde key representing the following characters.

Tilde = §
Tildie + shift = ½

I tested this with 2 other keyboard layouts (Swedish and Dvorak US) but both didn't trigger this error. So it must be something else that is to do with my keyboard layout.

![image](https://user-images.githubusercontent.com/68293755/231305031-3738e386-cb71-4fb4-b6c0-3f6eac1291ba.png)
Attached the keyboard layout I'm using myself.
I can share my keyboard layout (you could install or open it with Microsoft Keyboard Layout Creator) if you're interested. If not, I'd also be okay with closing this bug as the chance of this affecting someone else will be probably close to none.

**Comment by kvgelder** [comment]
Whoops, mis clicked the wrong button.

**Comment by pit-ray** [comment]
Sorry for my late reply.
If you can, please share your keyboard layout.
win-vind suffers from language problems due to the keyboard layout, so its details help for solving this.

Thanks a lot.

**Comment by kvgelder** [comment]
> Sorry for my late reply. If you can, please share your keyboard layout. win-vind suffers from language problems due to the keyboard layout, so its details help for solving this.
> 
> Thanks a lot.

https://filetransfer.io/data-package/xe1hT1cH#link

You should be able to edit/open the layout using the Microsoft Keyboard Layout Creator tool.

**Comment by pit-ray** [comment]
@kvgelder @Gabritorre 
Thank you all for information.
I confirm to reproduce it.
For now, I registered this issue as a top priority task.
So, when this issue is fixed, I release new version.
Thanks.
https://github.com/users/pit-ray/projects/2/views/6?pane=issue&itemId=11489613

**Comment by pit-ray** [comment]
Fixed at v5.2.3.
