### ISSUE TITLE
[Bug] ` to_gui_normal` changed to insert mode 

### ISSUE THREAD

**Issue by babaolanqiu** [pit-ray/win-vind#152]
# About Bug
1. I put this in my `.vindrc` (nothing else)
``` 
evnoremap <alt-f1> to_gui_normal
```
But when I press `<alt-f1>` in edi visual mode, it moved to insert mode instead of gui normal mode.
# Environments

|Environments| |
|:---:|:---|
|Windows Edition|[11 Home]|
|Windows Version|[22H2]|
|Windows Build|[22621.1485]|
|Architecture|[64bit]|
|win-vind Version|[5.0.1.0]|
|win-vind Install Type|[installer]|

**Comment by pit-ray** [comment]
The called function must be enclosed between `<` and `>`.
So, please try `evnoremap <alt-f1> <to_gui_normal>`.

**Comment by babaolanqiu** [comment]
That solved it. Thanks!
