### ISSUE TITLE
[Question] Working with surfingkeys

### ISSUE THREAD

**Issue by c4dr01d** [pit-ray/win-vind#156]
**Question**
Hi, I just installed win-vind today, when I use win-vind on my browser, vim-wind conflict my surfingkey extension, some function cannot normally to work, have any workaround for this?

**Comment by pit-ray** [comment]
The key bindings of win-vind are modifiable to your preferred ones. Therefore, if your browser shortcuts conflict with win-vind, I recommend defining maps to avoid duplications.

Thanks.

**Comment by c4dr01d** [comment]
Ok, thanks for answers
