### ISSUE TITLE
[Bug] Wrong location of caret after `c` + motion

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#157]
Caret location is misplace after `change + motion` command. Here's an example:

aaa [LOCATION OF CARET]bbb ccc ddd

After commdand: `cw` (change + one word forward), the location is here:

aaa bbb ccc [LOCATION OF CARET]ddd

-- although it should be here:

aaa bbb [START LOCATION OF CARET]ccc ddd

# Environments
Edition	Windows 10 Pro
Version	21H2
Installed on	‎3/‎13/‎2021
OS build	19044.2846
Experience	Windows Feature Experience Pack 120.2212.4190.0
|win-vind Version|5.0.0.5

**Comment by pit-ray** [comment]
@gilbh 
Thanks for your bug reports and sponsoring.

This behavior is exactly a bug.
Furthermore, this operation should remove one word, but the current behavior does not remove it.

I'll fix it as soon as possible.

**Comment by gilbh** [comment]
Thanks. 

About "the current behavior does not remove it" -- if you wrote this b/c of my example above, then it was my mistake, I forgot to remove the 'bbb' following the `cw` command. The correct behavior is this:

aaa [LOCATION OF CARET]bbb ccc ddd

After command: cw (change + one word forward), the location is here:

aaa ccc [LOCATION OF CARET]ddd

-- although it should be here:

aaa [START LOCATION OF CARET]ccc ddd

Sorry for the confusion!

**Comment by pit-ray** [comment]
Not your example, win-vind does not actually remove.

**Comment by pit-ray** [comment]
I solved this problem.
After passing some tests, I'll release it as v5.0.2.

**Comment by gilbh** [comment]
I just confirmed and now it works fine. That's a big help! Many thanks!!
