### ISSUE TITLE
[Bug] Switching windows causes it to scroll down a little bit

### ISSUE THREAD

**Issue by Salted-Bread** [pit-ray/win-vind#159]
# About Bug

Whenever I switch focus to another window using the CTRL+W, S shortcut it scrolls down a little bit. It's not a huge deal, but somewhat annoying at times.

# Steps to reproduce
1. Open a browser (Edge in my case)
2. Go to a site that allows scrolling (Youtube for example)
3. Un-focus the window by going to another window or focusing the desktop

# Environments

|Environments|Delete the example and fill in your information.|
|:---:|:---|
|Windows Edition|Windows 11 |
|Windows Version|22H2|
|Windows Build|22621.1555|
|Architecture|64bit|
|win-vind Version|5.1.0-beta1|
|win-vind Install Type|installer|

**Comment by pit-ray** [comment]
@Salted-Bread 
I could reproduce this problem.
It seems to be obviously a bug.

Thanks.

**Comment by pit-ray** [comment]
https://github.com/users/pit-ray/projects/2/views/6?pane=issue&itemId=28724177

**Comment by pit-ray** [comment]
Fixed.
