### ISSUE TITLE
Controlling the scroll movment size

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#16]
Hi again!

When I use the very helpful ctrl+y and ctrl+e, the scrolling of the window is very slow and choppy. It is possible to determine how many pixels each jump will have? If this is too much work to add this as a GUI feature for the user to determine, perhaps just increase it by a bit? (I am not sure if this is only in my computer or to my own taste...).

Best!

**Comment by pit-ray** [comment]
Hi, thanks!

The control exists in **Preferences > Settings > Scroll Page > Vertical Scroll Speed**. Please try it.
If you want more speed, change the value of `yscroll_speed` in `~/.win-vind/settings.json` directly. 

By the way, scrolling has already implemented constant acceleration.

**Comment by gilbh** [comment]
Works like a charm!
