### ISSUE TITLE
[Feature] Imrpove gridmove labels

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#161]
I love this feature!!

One small change: when starting to click the 3-letter sequence, the already-clicked letters disappear, which is great. However, the location of the remaining letters (one or two) is pushed back. To avoid that, replace the already-clicked letters with a space instead of removing them. See behavior example in Vimium -> f.

Thanks!!

**Comment by pit-ray** [comment]
I have implemented inserting a space in place of the deleted character.
However, the width of the space depends on the font, so a monospace font such as Consolas must be used.

## Arial
https://github.com/pit-ray/win-vind/assets/42631247/0ea1e2a2-c397-4dcd-a260-2dc6f73f11e9

## Consolas
https://github.com/pit-ray/win-vind/assets/42631247/f985d3fe-b1b7-4a59-a076-c65014e0a11e

Thanks.
