### ISSUE TITLE
[Feature] return to __RESIDENT__ after EASY CLICK

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#162]
The easy_click works great, but I think it makes sense to allow the user to automatically jump back to __RESIDENT__ or __EDIT_INSERT__ after completion of the click, because the user immediately want to act upon this.

Maybe add this as an option?

Thanks for the great work!

**Comment by pit-ray** [comment]
I implemented it.
In the next version, you can define following macros.

```vim
gnmap FF <easy_click_left><to_resident>
```

Thanks.

**Comment by gilbh** [comment]
Fantastic! Can't wait to try!
