### ISSUE TITLE
[Question] How to trigger EasyClick in insert mode?

### ISSUE THREAD

**Issue by kurtontheway** [pit-ray/win-vind#166]
**Question**
According to the description in the document, Easy Click can be used in insert mode. However, I've tried several times using the default shortcut keys (shift+f, shift+f) without success, while it works in GUI normal mode. Is there any other way to activate Easy Click in insert mode that I'm not aware of?

**Comment by gilbh** [comment]
This is how it works for me:

```
inoremap <f20> <easy_click_left>
inoremap <ctrl-8> <f20>
```

and so it is activated with `<ctrl-8>`

**Comment by kurtontheway** [comment]
Thanks @gilbh , that's a good idea!

**Comment by pit-ray** [comment]
@kurtontheway 
For versions after 5.0.0, `inoremap <ctrl-8> <easy_click_left>` is sufficient.

**Comment by gilbh** [comment]
You're right, old habits die slow!
