### ISSUE TITLE
[Bug] gridmove labes are not cleared from 2nd monitor

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#167]
I am really loving the new gridmove feature, which brings us closer (compared with easyclick) to completely stop using Vimium and relying on the gridmove for clicking screen object. Here's how I am doing this:
```
ennoremap f <gridmove><to_insert><click_left>
```

As for the bug: when a label is chosen (with typing the three letters combination) all the labels on monitor no. 1 are removed but on monitor no. 2 they remain on the screen (if I will refresh the screen they disappear, but they are not actively removed otherwise).

Edition	Windows 10 Pro
Version	21H2
Installed on	‎3/‎13/‎2021
OS build	19044.2846
Experience	Windows Feature Experience Pack 120.2212.4190.0

Vind: 5.1.0

**Comment by pit-ray** [comment]
In v5.4.0, I cannot reproduce this issue.
What do you think?
Thanks.

**Comment by gilbh** [comment]
Indeed, issue is not reproduced. Great!!
