### ISSUE TITLE
[Question] The status of `:source`?

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#168]
Hi,

Not sure if `:so` / `:source` is supposed to reset the settings, but again and again I find that if I remap keys, sourcing will not work properly, and I need to exit/reload vind to make the new key mappings work correctly. What am I missing here?

**Comment by pit-ray** [comment]
Early win-vind used to reset, but no longer does so as with Vim to allow another .vindrc to be called from within .vindrc.

```vim
" Load local .vindrc
source another.vindrc

" Load remote repository .vindrc
source pit-ray/remote_vindrc_demo
```
