### ISSUE TITLE
[Feature] adding `sleep` command?

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#169]
Is it possible to add a `sleep XXXm` command? I need for a sequence of actions:
```
enmap / <to_resident>{<alt-ctrl-f>}
```

-- so I need a pause between `to_resident` and the `{alt-ctrl-f}` (otherwise the second action fails).

Thanks!

**Comment by pit-ray** [comment]
Implementation is possible, but how to specify the time as a syntax is problematic.

For example, is it indicated by a prefix number?
```vim
enmap / <to_resident>32<sleep>{<alt-ctrl-f>}
```

Please let me know your opinions.

**Comment by gilbh** [comment]
Right!

Vim has it both ways (prefix and command parameter):
```
[N]sl[eep] [N][m]
```

Here are the options as I see it:

1) Having both is best, but might be too complicated to implement. 

2) If you have a command call syntax implemented in vind (e.g., `COMMAND_NAME VALUE`)? If the answer is yes, then I think that would be the 2nd best option:
```
enmap / <to_resident><sleep 32>{<alt-ctrl-f>}
```
or maybe
```
enmap / <to_resident><sleep>32{<alt-ctrl-f>}
```

3) Going with `32<sleep>` as you suggest above is fine too. 


Another issue to consider: if you can allow specifying *milliseconds*, it would be preferable. It would allow more accurate and allow shorter usages. (For example, in AHK I many times have `sleep 100` or `sleep 750` for milliseconds pauses). 

On this issue, there are two options:

1) you might have *both* seconds (as the default) and milliseconds (if `m` is specified after the numeric value).

2) you could have only milliseconds (to allow either less than or more than one second).

Best!

**Comment by pit-ray** [comment]
It looks like it can be implemented. I have started work on it.

https://github.com/users/pit-ray/projects/2/views/6?pane=issue&itemId=43590695

**Comment by pit-ray** [comment]
This features is merged into the master branch.
