### ISSUE TITLE
difference between EDI INSERT and GUI INSERT?

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#17]
Hi

I am asking this because it is much easier for me to remain in EDI INSERT while writing in Word and switch to other apps etc., than to need to switch to GUI INSERT every time I am doing something outside Word.

Thanks
Gil

**Comment by pit-ray** [comment]
Thanks again.

**GUI Insert**
There is only `change_to_insert` to transition it and the function generates left click event.

**Edi Insert**
There is a lot of ways to transition it like below.
- `change_to_edi_insert` (**i**)
- `change_to_edi_BOLinsert` (**I**)
- `change_to_edi_bkinsert` (**a**)
- `change_to_edi_EOLinsert` (**A**)
- `change_to_edi_nlinsert_below` (**o**)
- `change_to_edi_nlinsert_above` (**O**)

Both mode passes all inputs to Windows. In this points, there are no differences.

By the way, there is solution for your concern. Please try <a href="https://pit-ray.github.io/win-vind/cheat_sheet/options/#dedicate-to-one-window">Dedicate To One Window</a> option. 
You can enable it in `Preferences > Settings >  Options > Dedicate To One Window`.   
You can target one window. If then, transition to Edi Normal when you select the window and change to GUI Insert outside it automatically. Please try it.

**Comment by gilbh** [comment]
I will! Thanks!

I need to think some more about the identity between the two modes, maybe worth collapsing to one (for greater clarity, ease of use, etc.)? But let me try some more and make suggestions. 

This tool is amazing as it is.

**Comment by gilbh** [comment]
So I played around a bit with EDI Insert, which is very useful for typing -- I could not use GUI Insert for typing (which is obvious -- it is not meant for that clearly). But is there anything with GUI Insert can do which EDI Insert cannot?

**Comment by pit-ray** [comment]
> But is there anything with GUI Insert can do which EDI Insert cannot?  

No. There are no differences in both states themselves. In other words, they are a state only passing inputs to Windows. The differences are just transition functions.

Why is there the same mode? It's because of using as preset-groups depending on the situation. For example, we use `<Esc>` in many popular game applications. If there are only **Edi Insert** and start-up with **Edi Insert**, the `<Esc>` typing is reacted by `change_to_edi_normal`. In the end, we won't be able to input with the keyboard unintentionally. Thus, **GUI Insert** is needed as a resident mode. 

Do you have another solution?

**Comment by gilbh** [comment]
Yes, I had exactly this situation working in .... guess what? .... Vim!! Hitting Esc to switch modes inside Vim suddenly took me from EDI Insert to EDI Normal .... which is not good. I will now try using GUI Insert and GUI Normal instead....

Thanks!

**Comment by pit-ray** [comment]
Please try <a href="https://pit-ray.github.io/win-vind/cheat_sheet/options/#suppress-for-vim">Suppress for Vim</a> option!!

**Comment by gilbh** [comment]
So this exactly handles the situation of EDI Insert in Vim, correct?

**Comment by pit-ray** [comment]
In any mode, if you select a window that includes `vim` in the program name (e.g. vim.exe, gvim.exe, nvim.exe), it will automatically change to **GUI Insert**. However, automatic return from **GUI Insert** to **Edi Insert** is not implemented yet. The implementation is possible.

**Comment by gilbh** [comment]
I would need a bit more practice time to check this. But I think it might be confusing to create a "shortcut" from GUI Insert to Edi Normal just for Vim application....I will try to give feedback after working some more with the "Suppress for Vim" option on.
