### ISSUE TITLE
[Feature] Select own hints.

### ISSUE THREAD

**Issue by lucordes** [pit-ray/win-vind#172]
I would like to select my own set of characters of wich the hints are made of.
It would be nice to set those characters. It makes sense to chose the characters that are positioned on the homerow on the keyboard.
Surfingkeys implements this nicely.
https://github.com/brookhong/Surfingkeys#follow-links

**Comment by pit-ray** [comment]
Thanks for feature requests.
That feature will allow win-vind to support various keyboard layouts.

I'll implement it.

How about the parameter name `hintkeys`?

```vim
set hintkeys = abcdefghijklmnopqrstuvwxyz
```

**Comment by pit-ray** [comment]
Implemented.

**Comment by lucordes** [comment]
Works like a charm <3.
