### ISSUE TITLE
[Bug] wrong version in About

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#175]
I noticed now that the About of the latest release: v5.1.0 beta shows the following information:
![image](https://github.com/pit-ray/win-vind/assets/39532610/c7c4ddb5-8089-4f5d-911f-04a2f8f297a4)

It helps to keep the version information up-to-date, especially with beta releases and such, since we are trying new features and jump back and forth between versions. Thanks!!

Edition	Windows 10 Pro
Version	22H2
Installed on	‎3/‎13/‎2021
OS build	19045.2965
Experience	Windows Feature Experience Pack 1000.19041.1000.0

win-vind Version|[e.g. 4.0.0]| : v5.1.0 (but shows 5.0.3.0......)
(Portable)

**Comment by gilbh** [comment]
Interesting. I just now checked again: I downloaded this portable version:
https://github.com/pit-ray/win-vind/releases/download/v5.1.0-beta1/win-vind_5.1.0-beta1_64bit_portable.zip

and ran it from a new folder -- still it shows:
![image](https://github.com/pit-ray/win-vind/assets/39532610/c944f0c1-347c-4665-8fbf-fe312ab7783b)

**Comment by pit-ray** [comment]
@gilbh 
I fixed the version at #163, but have not replaced that build. I will be releasing a new version soon, so forgive its wrong version of 5.0.3.

**Comment by gilbh** [comment]
Sure thing. This is more for informative purpose, no harm done and thank you for all the good work!!
