### ISSUE TITLE
[Question] double bindings?

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#18]
Hi,

I added a binding to guii as <alt-i> but when I type this I first get a notice:
-- TARGET ON --

Is this overstepping another binding? I could not figure it out...

Thanks.

**Comment by pit-ray** [comment]
Thanks.

The message is given by `enable_targeting_of_dedicate_to_window`, so some bindings are duplicate with this. 
URL: [Cheet Sheet/Others/Enable Targeting](https://pit-ray.github.io/win-vind/cheat_sheet/others/#enable-targeting)
