### ISSUE TITLE
[Feature] EasyClick to work on *all visible apps* and not just app in focus

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#181]
This would be similar to GridMove and will allow to send a command (or do something) even when the app is not the one in focus.

**Comment by pit-ray** [comment]
It can be implemented, but it will take quite a bit of scanning time.
Please try running EasyClick with a few/many cells displayed in MS Office Excel. It will take a tremendous amount of time as the number increases.

Therefore, we cannot achieve this feature.

**Comment by gilbh** [comment]
I ran Excel and clicked EasyClick. The labels appears almost instantaneously. I wish I could show you this via the Video Capture feature, but vind's labels are not visible in the video recording. I would estimate it in about 200ms (for hundreds of labels, one for each cell, etc.). Maybe the scanning time changes radically according to hardware and software features. 

But I am not underestimating your concern. Perhaps you would consider creating a *separate* command (EasyClickAll) so to leave the option of using this slower function ... ? I think it would be amazing to be able to control *everything* visible, even if slower response, and leave that choice to the user according to how "busy" the open apps are at a given moment.

Let me know your thoughts.

Thanks!

**Comment by azinsharaf** [comment]
hi, I am not using Excel but i use multiple apps (tiled with a windwos manager) so that would be nice to have the hint for al lthe visible apps in the screen.

**Comment by pit-ray** [comment]
@gilbh @azinsharaf 
For now, we will try to implement it and then benchmark it.

**Comment by pit-ray** [comment]
I added it to the taskboard.
https://github.com/users/pit-ray/projects/2/views/3?filterQuery=-status%3ADone-status%3ADone%2CCanceled%2CDone&pane=issue&itemId=35722208

**Comment by pit-ray** [comment]
@gilbh @azinsharaf 
I implement `<easyclick_all>` to work on all visible applications.
`<easyclick_all>` is binded with `AA`, `Ao`, `Aa`, `Am` and `Ah` in GUI normal mode, which is based on `<easyclick>`.
Please try this build and give me feedbacks.

[win-vind_issue181_64bit_installer.zip](https://github.com/pit-ray/win-vind/files/12326983/win-vind_issue181_64bit_installer.zip)
[win-vind_issue181_64bit_portable.zip](https://github.com/pit-ray/win-vind/files/12326984/win-vind_issue181_64bit_portable.zip)

**Comment by gilbh** [comment]
From what I am seeing, this works fantastic!!

**Comment by pit-ray** [comment]
Released in v5.4.0

**Comment by shuen2023** [comment]
> 据我所见，这效果太棒了！

Sorry to bother you! Can you tell me how to use it?  I just set up map fg <easyclick_all> and it seems that it recognizes some more programs than the original one. This is the default ctrl+[ in edit mode, but how do I open the selected program?  Switch to gui mode ctrl+]?

**Comment by gilbh** [comment]
Not sure I understand the problem ... as far as I understand there is no need to open or switch: when you click the specific letters sequence it will switch automatically.

**Comment by azinsharaf** [comment]
> Released in v5.4.0

thanks @pit-ray

**Comment by shuen2023** [comment]
> > 据我所见，这个效果太棒了！
> 
> 很抱歉打扰你！你能告诉我如何使用它吗？我刚刚设置了map fg <easyclick_all>，它似乎比原来的程序识别更多的程序。这是编辑模式下默认的ctrl+[，但是如何打开选定的程序呢？切换到 GUI 模式 ctrl+]?

OK,thanks..

**Comment by shuen2023** [comment]
> Released in v5.4.0

Forgive me for continuing to reply below this.  I also think this improvement is great.  But I don't know why, all I see on my side is the mouse moves.  But the program cannot be opened directly.  Is there something wrong with my configuration?  I recorded a video.  I am using the win11 enterprise personal modification system.  I can open the program directly after configuring FF, but I can only see that it has moved to the target position and cannot open it in my <easy_click_all> of FG.    


https://github.com/pit-ray/win-vind/assets/133501179/4fb55c18-0591-4ff9-a92e-7cdab7a0c413

**Comment by shuen2023** [comment]
> 不确定我是否理解这个问题......据我所知，不需要打开或切换：当您单击特定的字母序列时，它会自动切换。

thanks!

**Comment by pit-ray** [comment]
@shuen2023 
Thanks for asking about that.
If I catch your question correctly, you should add `<click_left>` after `<easyclick_all>`.
```vim
map fg <easyclick_all><click_left>
```

Very confusingly, the easyclick itself does not have a click function.

Previously, there are the easyclick families, such as  `<easy_click_left>` or `<easy_click_right>`. However, this specification is redundant, so they have been unified to `<easyclick>` since 5.1.0.
For compatibility, the name `<easyclick>` contains the word `click`, but it does not perform a click, as does the previous `<easy_click_hover>`.

https://pit-ray.github.io/win-vind/cheat_sheet/functions/#easyclick

Thanks.
