### ISSUE TITLE
Is there no way to list all key controls or "help?"

### ISSUE THREAD

**Issue by NotRexButCaesar** [pit-ray/win-vind#183]
**Question**
The command "help" returns the error "Not a command", and I do not see anything on the website indicating a way to list key controls or help.  Is there a method within the program to list the contextually possible key controls or if not that then all key controls?

**Comment by pit-ray** [comment]
The help command is not implemented yet. (#59)
So, for now, you can refer to the online document in [website](https://pit-ray.github.io/win-vind/cheat_sheet/).
