### ISSUE TITLE
[Feature] Adding distinction: `left_shift` and `right_shift`

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#184]
I am trying to do this in `.vindrc`:
```
ennoremap <alt-left_shift> <to_resident>{alt-shift_left><to_edi_normal>}}
```

-- and am getting this error:
![image](https://github.com/pit-ray/win-vind/assets/39532610/3ea41a9d-8054-4e2b-95c3-43e8fdca60b1)

(the reason for this mapping is just to pass an <alt-left_shift> event to another app, see my feature question #177).

Is there distinction between left and right shifs/ctrl/etc.?

Thanks for your help!

**Comment by pit-ray** [comment]
Please see this document.
https://pit-ray.github.io/win-vind/cheat_sheet/keywords/#system-keyword

You can use `<rshift>` and `<lshift>`.

**Comment by gilbh** [comment]
Indeed!

I see that this is under "keywords" and I was looking under "usage." After I get into getting Jekyll to work I will try sending some PR to make documentation more explicit.

Thanks for all the help!
