### ISSUE TITLE
[Bug] mapping `<alt-->` (with minus key)

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#185]
When I try to source this:
```
ennoremap <alt--> <to_resident>{<alt--><to_edi_normal>}
```

I get an error:
![image](https://github.com/pit-ray/win-vind/assets/39532610/c8718f33-8948-4cbe-b3cc-e06a27d59677)

--although this works fine:
```
ennoremap <alt-=> <to_resident>{<alt-=><to_edi_normal>}
```

Thanks!

**Comment by pit-ray** [comment]
please see this document.
https://pit-ray.github.io/win-vind/cheat_sheet/keywords/#specific-ascii-keyword
You can use `<hbar>` instead.

**Comment by gilbh** [comment]
I am so impressed by the coverage of vind, you thought of it all!!

But it's not the first time I am unable to find something in the documentation -- I hope to contribute there with time.

Thanks!!
