### ISSUE TITLE
[Feature] Tab Completion for Commands

### ISSUE THREAD

**Issue by kumkee** [pit-ray/win-vind#186]
**Describe the feature you'd like**
Like in vim, pressing the Tab key after typing in a command fragment would give you a list of commands, containing/beginning with that fragment, to choose.

**Related projects (Optional)**
The existing projects with a similar feature that you can think of.
- vanilla vim or [with plugins](https://www.baeldung.com/linux/vim-autocomplete).
-  [bash-completion](https://github.com/scop/bash-completion)
- [zsh-completions](https://github.com/zsh-users/zsh-completions)

**Comment by pit-ray** [comment]
Thanks for feature request.

The features that you proposed is exactly what is needed.
In particular, `:!` command can be useful application launcher by linking to the terminal enviroment variable or path solving system.

For now, I put it into ToDo List.
https://github.com/users/pit-ray/projects/2/views/6?pane=issue&itemId=33379819

If you can develop it, pull requests are wellcome!
When I'll participate in the implementation for this feature when I have time.

**Comment by pit-ray** [comment]
@kumkee 
This feature was implemented.
It will be available in v5.9.
