### ISSUE TITLE
[Question] How do I use <click_mid>?

### ISSUE THREAD

**Issue by Salted-Bread** [pit-ray/win-vind#188]
I often like to open things in a new tab with the middle mouse click, but I'm unable to bind it in my config.

I read that <click_mid> is supposed to be a thing here: https://pit-ray.github.io/win-vind/cheat_sheet/functions/#click_mid

But trying to add a keybind for <click_mid> just throws up an error saying it's unsupported. However, <easy_click_mid> works fine.

**Comment by pit-ray** [comment]
Do you use the latest win-vind?

If you write like the following, the middle mouse click is available.
```vim
map b <click_mid>
```

**Comment by Salted-Bread** [comment]
I'm using the latest version and sadly it's still not working.

I tried `map b <click_mid>`, but it still errors out.

[Here is a screenshot of the error](https://i.imgur.com/z9U2sK2.png)

**Comment by pit-ray** [comment]
Your screenshot shows the function scope as an error message, but I removed such scope prefixes from the win-vind for a more concise error message in the latest version.
Therefore, I think you use the old win-vind.

Could you check the version of win-vind again?
You can confirm the version at **About** in the popup menu.

**Comment by Salted-Bread** [comment]
Installing the newest version did fix the issue. I must have misremembered updating to a newer version. Apologies for the inconvenience.
