### ISSUE TITLE
AHK

### ISSUE THREAD

**Issue by dellas60** [pit-ray/win-vind#189]
WHEN I PUT THIS LINE IN AHK 
#f::Run, win-vind --func easy_click_left
I GET THIS ERROR

![AHK](https://github.com/pit-ray/win-vind/assets/29574213/7f82ada9-89ad-4662-a6d8-035fabc7c24a)

**Comment by gilbh** [comment]
It looks like your AHK is unable to find "win-vind" without specific the path in which it is installed.

Either:
1) specify the full path in the AHKL "Run" command, like this:
Run, "C:\Program Files\win-vind\win-vind.exe" "--func" "easy_click_left"
[notice the quotation marks, and change to the path your win-vind is installed in].
or:
2) make sure win-vind is in the %PATH% system variable. Look up how to add a path to the system/user %PATH% variable, and check if it is updated from the command line like this:
c:\> echo %PATH%
[but notice that system variables are not updated immediately, simplest way to refresh is restart to the system]

Let me know if helps.

**Comment by dellas60** [comment]
thank you probleme solved
