### ISSUE TITLE
[Feature] embedding AHK scripting in Vind?

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#199]
These are just preliminary thoughts about the next generation of Vind, hoping to spawn a brainstorming conversation (if at all relevant).

It is obvious that Vind and AHK fulfill similar functionality, although with completely different philosophy: Vind embeds Windows in a Vim-like environment, and AHK runs macros with sophisticated scripting. 

How difficult is it to embed the scripting engine of AHK into Vind? Is it open source etc.? Will Vind adopt vimscript or lua? Or does it make sense to try and unite the AHK scripting language in Vind?

Best!

**Comment by pit-ray** [comment]
The current win-vind is already complex enough, and the biggest challenge now is to reduce the learning cost. Therefore, I'm not considering embedding an AHK script engine, as it would be very complex to implement.

**Comment by gilbh** [comment]
Yes, indeed! Best
