### ISSUE TITLE
[Question] What is the best way to force CapsLock to Ctrl for win-vind?

### ISSUE THREAD

**Issue by simplygood** [pit-ray/win-vind#20]
**Question**
What is the best way to force CapsLock to Ctrl for win-vind? I used PowerToys, but it doesn't seem to work very well. Thanks!

**Comment by pit-ray** [comment]
The current win-vind does not support hotkey and only supports pre-defined functions. However, will support in the next 4.x.x version with .vimrc like syntax.

By the way, the CapsLock is a toggle key. If we get the key state in low level to absorb inputs in order not to pass key messages to other application, we are hard to recognize the toggle state with hardware dependent. However, if not absorb, it's easy. Thus, now the implementation of win-vind is ignoring CapsLock. I will try to commit to supporting toggle keys for 4.x.x. version.

**Comment by simplygood** [comment]
A registry method worked well, btw. Thanks and look forward to more native support in the future!

**Comment by pit-ray** [comment]
Ok. I keep it in mind as one method. I will try to find another method to do it within user permission.
