### ISSUE TITLE
[Feature] request for functions like <move_window_left>

### ISSUE THREAD

**Issue by longguzzz** [pit-ray/win-vind#202]
**Describe the feature you'd like**
I am configurating my vindrc file. I found that command sequence like `:resizer<cr>ej<esc>` or `<window_resizer>ej<esc>` does not work. So, moving window needs use resizer' move mode and can not be simplified without something like <move_window_left>

**Comment by pit-ray** [comment]
Sorry for my late reply.
You are right. I will implement it.

**Comment by pit-ray** [comment]
This feature was implemented. It will be available in v5.7.0.
