### ISSUE TITLE
[Question] Entering Insert mode triggers mouse_left_click action

### ISSUE THREAD

**Issue by ziombo** [pit-ray/win-vind#203]
**Question**
When I enter Insert mode (at least from GUI Normal) a mouse left click action is triggered. Is this expected and is it possible to prevent this?

**Comment by pit-ray** [comment]
Hi.
This behavior is expected one, because I assumes the usage which the mouse cursor is moved onto the target window in GUI normal mode and select the window to insert some text.

To avoid this, you can use the following settings.

```vim
gnnoremap i <to_insert>
```

**Comment by ziombo** [comment]
Thank you, works like a charm
