### ISSUE TITLE
HINTS ISSUE

### ISSUE THREAD

**Issue by dellas60** [pit-ray/win-vind#204]
Hi,
When i set hintkeys = 123456789 and press numpad there is nothing happening.

**Comment by pit-ray** [comment]
HDid you try executing `:source` after you rewrote the .vindrc? In my environment, hints were assigned.

**Comment by Salted-Bread** [comment]
Can confirm this issue on my end. Assigning numbers to the hints only allows me to select them with the number row at the top of my keyboard, not the numpad.

It also causes the program to completely glitch out for me. Typing the numbers of a hint on the numpad causes them to flash for a moment and then re-appear. When I then select them with the number row it selects the item, but the hints appear again, but this time they won't disappear. Closing the program, resetting graphics driver and restarting explorer.exe all didn't work. Ended up having to restart my PC to make it go away.

https://i.imgur.com/wEydBT7.jpeg

**Comment by pit-ray** [comment]
@dellas60 
I misunderstood this issue.
As @Salted-Bread says only the main keyboard is allowed.
Currently, win-vind does not support numpad.
