### ISSUE TITLE
[Question] How to set shell to wsl

### ISSUE THREAD

**Issue by ZreXoc** [pit-ray/win-vind#205]
I try to set shell to wsl, but neither
```
set shell = wsl
```
nor
```
set shell = "wsl --"
```
works.

OS: Win11
wsl version: 1.2.5.0
wsl: [ArchWSL](https://github.com/yuk7/ArchWSL)

**Comment by pit-ray** [comment]
Please try `set shellcmflag` as the following.

```vim
set shell = wsl
set shellcmdflag = --
```
Thanks.

**Comment by ZreXoc** [comment]
Thanks! It works
