### ISSUE TITLE
[Bug] Unable to get rid of blockstylecaret 

### ISSUE THREAD

**Issue by Salted-Bread** [pit-ray/win-vind#225]
# About Bug
Recently the blockstylecaret has been active all over Windows whether the program is running or not. I tried to change it in the config by setting `set blockstylecaret = false`, but it seemed to have no effect. Re-installing and reverting to an older version didn't seem to have any effect either. Not even entirely sure if win-vind is fully at fault here, but I don't have anything else that's supposed to do that.

# Steps to reproduce
Not too sure since it just kinda started happening out of nowhere and I can't revert it, so figuring out what exactly caused it is hard.
1. `set blockstylecaret = true`
2. `set blockstylecaret = false`
3. blocksytlecaret is still visible no matter what mode is running or even with the program closed.

# Environments

|Environments|Delete the example and fill in your information.|
|:---:|:---|
|Windows Edition|Windows 11 Home|
|Windows Version|23H2|
|Windows Build|22631.3085|
|Architecture|64bit|
|win-vind Version|5.10.0.0|
|win-vind Install Type|installer|

**Comment by pit-ray** [comment]
@Salted-Bread 
The bool options must change `no` prefix instead of `=false` as described in [usage](https://pit-ray.github.io/win-vind/usage/#change-parameters-and-options).
Therefore, please try `set noblockstylecaret`.
Thanks.
