### ISSUE TITLE
[Bug] imap <Capslock> <ctrl> not work....

### ISSUE THREAD

**Issue by lihz** [pit-ray/win-vind#23]
win-vind\config\.vindrc

imap <Capslock> <ctrl>

It doesn't seem to be working properly in Insert Mode.

- Windows 10 Edition:  Pro
- OS Type: 64bit
- OS Version: 2004

**Comment by pit-ray** [comment]
Just like Vim, only rewriting the .vindrc doesn't work. You can reload it by restarting win-vind or typing
```
<F8>:so
```
in Insert Mode. if there is any syntax error, all will be output to `win-vind/log/`.

If this doesn't work, try typing
```
<F8>:imap <capslock> <ctrl>
```
in Insert Mode to see if it works temporarily.

Otherwise, this problem may be an undiscovered bug, then I will patch it as soon as possible.

Thanks.

**Comment by lihz** [comment]
Hi pit-ray!

I found the "win-vind" a few days ago and have been using it very hard. 
Thank you very much for this great (really...) software being available for free.

Yes, I know to need ":source" action after modifying .vindrc and, of cause done
But.. have no effect...

( I have 2 PC, office and home,, install win-vind to them, and have same result. )

**Comment by pit-ray** [comment]
Thanks for using it, and reporting.

I'd like to reproduce the problem to solve it. Can this problem be reproduced in the following steps?
1. download the **zip version**
2. open .vindrc from the menu **Open Root Directory** in system tray.
3. write `imap <capslock> <ctrl>` into the first line of .vindrc.
4. do `:source`

It may be an environment-dependent problem, so could you please check the log file in `win-vind/log/error_2021*.log`.

By the way, does the `:imap` command from **Virtual Command Line** work?

Thanks.

**Comment by lihz** [comment]
I found that what I posted before was not a bug.
I modified the default_config/bindings.json file, and I knew [imap <capslock> <ctrl>] didn't work after that.

----------------------------------------------
change <"Esc-Right"> to <"Ctrl-[">
 {
        "name": "to_edi_normal",
        "cdef": ["edinormal", "en"],
        "endef": [],
        "evdef": ["<Ctrl-[>"]
        "gndef": ["I", "<Ctrl-[>"],
        "gvdef": [],
        "idef": ["<Ctrl-[>"],
        "rdef": ["<Ctrl-[>"],
        "en": "Normal Mode (Vim Emulation: <Esc>)",
        "ja": "?롢꺖?욁꺂?㏂꺖??(Vim ?ⓦ깱?γ꺃?쇈궥?㎯꺍: <Esc>)"
    },
------------------------------------------------

Let's close the issue.

**Comment by pit-ray** [comment]
Modifying `default_config/bindings.json` directly is more efficient, but not recommended. All values in `default_config/bindings.json` can be overridden using .vindrc.

For example, your sample is able to convert to next .vindrc.

```vim
evnoremap <Ctrl-[> to_edi_normal
gnnoremap <Ctrl-[> to_edi_normal
inoremap <Ctrl-[> to_edi_normal
rnoremap <Ctrl-[> to_edi_normal
```

Thanks!
