### ISSUE TITLE
[Bug] new right menu does not work with arrows, only mouse clicks

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#235]
Recent versions (this one is 5.11.3) have a new right click menu:
![image](https://github.com/pit-ray/win-vind/assets/39532610/af7b7904-bd62-4868-9d71-ade0133d1bf5)

It does not work with arrows. This creates an issue b/c I have AHK macros for exiting and reloading vind everytime I change the .vindrc

Is it fixable? Maybe getting back to the previous menu (such as in version 5.8)?

Thanks

**Comment by pit-ray** [comment]
This problem is a lack of functionality on the [fluent-tray](https://github.com/pit-ray/fluent-tray) side. Please wait for an update of fluent-tray.

If you want to exit win-vind externally, `win-vind.exe -c "<exit>"` is sufficient.

**Comment by gilbh** [comment]
Amazing. Thanks!!

**Comment by pit-ray** [comment]
Now fluent-tray supports arrow-selection. https://github.com/pit-ray/fluent-tray/releases/tag/v0.5.0
