### ISSUE TITLE
[Question] Why is Gridmove using longer labels than would suffice.

### ISSUE THREAD

**Issue by Guscccc** [pit-ray/win-vind#240]
**Question**
First of all, thanks for your work! I've been searching for something like win-vind for quite a while, and loved it!

But when I was trying to use the Gridmove, I noticed that it is using longer labels than would suffice. 

For example, I have `set gridmove_size=20x30` in the `.vindrc`, which would need 600 distinct labels to fill out, and since the default value of `hintkeys` is all the 26 letters, which provides 26x26=676 labels using just 2 letter combinations, technically all the labels should use just 2 letters. But they use 3 letters for my case, and all of which starts with the same letter `A`, seemingly redundant.

Is this intended behaviour? If not, can it be fixed so that only as many as needed letters are used for labelling?

**Comment by pit-ray** [comment]
gridmove assigns a hint for each monitor, then assigns a unique hint sequence. This allows you to only have to pay attention to the target monitor after you have entered the first letter.
https://github.com/pit-ray/win-vind/blob/b68bc03c5992519dba5a7ee86c124f0cf44afca9/src/bind/mouse/gridmove.cpp#L100-L140

It can be modified to assign only the required strings, but there is a drawback to search hints.

**Comment by Guscccc** [comment]
Got it, Thank you very much for answering!
