### ISSUE TITLE
WinVind stops when right-clicked in tray [Bug]

### ISSUE THREAD

**Issue by Positron010** [pit-ray/win-vind#25]
**Describe the bug**
Recently, whenever I right click the win-vind icon in the tray, the app closes. This wasn't the behavior before, where a menu appears with options like showing the configuration file location. This issue is only with win-vind, all other icons show their menus.

**Environment (please complete the following information):**
- Windows 10 Edition: Home
- OS Type: 64bit
- OS Version: 10.0.19042 
- OS Build: Build 19042
- win-vind Version: 4.0.1
- win-vind Type: installer
- Is it reproducible?: Not sure

**What I tried:**
- Uninstalling/installing
- Removing my .vindrc file
- Restarting the computer

Thanks

**Comment by pit-ray** [comment]
Thank you for using it!
Are there any errors in `~/.win-vind/log/error_*.log` after it?

**Comment by Positron010** [comment]
Hi,
Thanks for replying.
There is an error log file, but it's unfortunately empty.
Thanks.

**Comment by pit-ray** [comment]
Thanks, I understand.

When right-clicking on the tray icon ([code](https://github.com/pit-ray/win-vind/blob/v4.0.1/coregui/src/tray.cpp#L86:L103)), win-vind scans shortcut files in the startup folder ([code](https://github.com/pit-ray/win-vind/blob/v4.0.1/coregui/src/startup.cpp#L75:L110)) and show a checkmark of **Startup with Windows** in the popup menu. I guess that the scanning was crashed for some reason.

So, please try opening the folder by `shell:startup` with Win+R and delete the win-vind shortcut files manually.

![winr_shell_startup](https://user-images.githubusercontent.com/42631247/124790121-dd37d400-df85-11eb-9c4b-ff46bc0b8237.jpg)

By the way, also try [the zip version](https://github.com/pit-ray/win-vind/releases/download/v4.0.1/win-vind_4.0.1_64bit.zip) to see if there is the same problem, and check log files as well.

If these solution does not work, I will try my best to debug and test.

I hope it works.

**Comment by Positron010** [comment]
Hi,
Unfortunately, neither methods worked :( .
Thanks

**Comment by Positron010** [comment]
To confirm that it is not an app interfering, I booted in safe mode, and the same issue persists. 

Thanks

**Comment by pit-ray** [comment]
Hi, thank you for trying everything. I will try to further the logic test.

I ran on three different computers in the same environment as yours, but could not reproduce.

If you allow it, we find the cause by running win-vind for debug. In this case, you can either run the debug build I prepared (open source, of course), or build and debug the code in the popup section programmatically in your environment.

Thanks.

**Comment by Positron010** [comment]
Hi,
Thanks for replying.
I am really not sure why this happens. It was working perfectly before.
Where can I find the debug version of the app? I am not that technical, so I would be grateful if you could provide me with detailed steps.
Thanks again.

**Comment by pit-ray** [comment]
I built debug version to log the behavior right-click and crashing.

Here are the steps.

1. Download this version [win-vind_4.0.1_issue25_1_64bit.zip](https://github.com/pit-ray/win-vind/files/6784964/win-vind_4.0.1_issue25_1_64bit.zip). BTW, code is [here](https://github.com/pit-ray/win-vind/tree/logcollect).
2. Unzip it and place it in the user permission directory (e.g. ~/Desktop)
3. Execute it and right-click on its icon in the tray.
4. Copy the texts of `win-vind/log/error*.log` and share them with me. However, since the user name will be collected, so please show it in a limited public scope (e.g. [Gist Private](https://gist.github.com/)).

I hope it works.

Thanks

**Comment by Positron010** [comment]
Hi again,
I can confirm that it was an issue from my side. I reset my Windows 10 OS, and Win-Vind now functions normally. However, from my humble investigation, the issue **might** be related to `ntdll.dll`.  Thanks for your cooperation and support. I hope no one faces this issue again. Thanks for making this great piece of software.

Kind regards

**Comment by pit-ray** [comment]
I'm glad it works!
I wish I knew the cause of the problem... I'll investigate using the `ntdll.dll` as a clue more.

Thanks for your contribution and the sponsorship!
Please let me know if you have any more problems. Thanks!
