### ISSUE TITLE
Potential Collaboration Opportunity

### ISSUE THREAD

**Issue by warpath20arrow** [pit-ray/win-vind#254]
Hi there, your work is quite impressive. Let's connect to discuss a potential opportunity. 

Telegram: @verecke1
Discord: vereckel
WhatsApp: +44 7341 822373

**Comment by pit-ray** [comment]
I believe that open source should be developed in an open forum and discussions are no exception.Therefore, please use Issues and Discussions on GitHub, not discord, and send pull requests.
