### ISSUE TITLE
Proposal for Consideration

### ISSUE THREAD

**Issue by enderdespellcaster** [pit-ray/win-vind#255]
Hi, I find your work remarkable! I have a potential opportunity I’d like to discuss. Can we connect? 

Telegram: @the_vereckel
Discord: vereckel
WhatsApp: +44 7341 822373

**Comment by pit-ray** [comment]
I believe that open source should be developed in an open forum and discussions are no exception.Therefore, please use Issues and Discussions on GitHub, not discord, and send pull requests.
