### ISSUE TITLE
[Bug] _windows_resizer_not_working

### ISSUE THREAD

**Issue by kbilsted** [pit-ray/win-vind#267]
# About Bug

when using the configuration

```
nmap <Control-w> <window_resizer>
```

the application wont start and i have a logfile

```
========== System Infomation ==========
[Windows]
      Edition: Windows 10 Pro
      Version: 22H2
Build Numbers: 10.0.19045
 Architecture: x64

[win-vind]
      Version: 5.13.2.0
=======================================
[Message] Version: huge
[Error] An logic exception occurred: control is not supported. (int __cdecl WinMain(struct HINSTANCE__ *,struct HINSTANCE__ *,char *,int))
```

Errors also for

`<switch_window>` and `<select_left_window>`  also errors when using `version big`

**Comment by kbilsted** [comment]
Ok i finally found out it means that the keyword "Control" is not supported. Perhaps it should say `keyword 'Control' not understood`

**Comment by pit-ray** [comment]
Use the following keywords for key codes.
https://pit-ray.github.io/win-vind/cheat_sheet/keywords/

**Comment by kbilsted** [comment]
Yes, please consider improving the error message - perhaps even supply that url in the error message,
