### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by Positron010** [pit-ray/win-vind#28]
Hi,
In this [page](https://pit-ray.github.io/win-vind/cheat_sheet/resident/) about `resident mode` the default binding to switch to `insert mode` should be <kbd>esc + up</kbd> rather than <kbd>esc + down</kbd>, which is what is describe in the mode transition image in this [page](https://pit-ray.github.io/win-vind/usage/).

Thanks

**Comment by pit-ray** [comment]
If document, you can send a pull request directly. Thanks.

**Comment by Positron010** [comment]
Hi,
I didn't find the documentation folder in the master branch, so I thought it wasn't uploaded. Apparently it is on another branch, it would be helpful if you stated that in the documentation or the readme file, or add to the master branch.

**Comment by pit-ray** [comment]
Hi.
Sorry for the poor documentation. I added the details to the readme. The documentation is on the `gh-pages` branch, and can be written in Markdown.

**Comment by pit-ray** [comment]
The documentation source has been moved to the docs directory of the master branch.
