### ISSUE TITLE
Change caret size to reflect different modes[Feature]

### ISSUE THREAD

**Issue by Positron010** [pit-ray/win-vind#31]
**Describe the feature you'd like**
Sometimes it is helpful to know which mode one is in. For example, it would be great if the **caret (insertion point)** changes to **block style** like in the terminal to reflect that you entered _normal mode_ just like in **Vim**, and then returns to the normal **thin mode** in _insert mode_. It would be helpful also to have a key binding to trigger the **status indicator** to reveal the _current mode_ **(just like the one that appears when switching modes)**. This is helpful especially for the _GUI Modes_.

Thanks and appreciate your work.

**Related projects (Optional)**
A similar project that implements **Vim** using _AutoHotKey_ ([vim_ahk](https://github.com/rcmdnk/vim_ahk)), has the _caret width_ feature as an option.

**Comment by pit-ray** [comment]
Thanks for the request.

The Binding that bring up the current mode is easy to implement. However, there are two concerns with implementing a block-style caret.

Firstly, **vim_ahk** only dynamically changes `Settings > Ease of Access > Cursor & pointer > Cursor thickness` on Windows 10, which has no effect on applications that have their own rendering (e.g. Chrome, Edge). Therefore, the support is likely to be uneven. Secondly, if it goes further than **vim_ahk** and changes the thickness that matches the size of the text, the character width detection will be a major problem.

Once I make a prototype, I will reply again.

Thanks

**Comment by sunladen** [comment]
Instead of changing Caret (cursor), would an easier solution be to switch application icon design in system tray?

Like "Vi" where the "i" is overlaid in front of the "V" and is a prominent bold colour to make it stand out from the "V". Some for other modes "Vgn", "Vgv", and so on...

**Comment by pit-ray** [comment]
> Instead of changing Caret (cursor), would an easier solution be to switch application icon design in system tray?
> 
> Like "Vi" where the "i" is overlaid in front of the "V" and is a prominent bold colour to make it stand out from the "V". Some for other modes "Vgn", "Vgv", and so on...

I am not very motivated to dynamically change the system tray icon like vim_ahk. This is because some people have grouped system icons or hidden the taskbar to make the icons invisible. But it might be a good idea to implement it as an option.

By the way, if you make the value of the [cmd_fadeout](https://pit-ray.github.io/win-vind/cheat_sheet/options/) option large enough, you can make the virtual command line not disappear.

For example
```vim
set cmd_fadeout = 3600 " one hour visible
```

**Comment by pit-ray** [comment]
Today, I released [v4.2.0-rc1](https://github.com/pit-ray/win-vind/releases/tag/v4.2.0-rc1) as the preview version. It supports block-style carets. However, it was difficult to detect the character width dynamically, so we implemented a width-fixed block style and a pseudo block style with selection instead.  Please give it a try.

**Comment by Positron010** [comment]
Hi,
Thanks for you hard work. I really appreciate your efforts.
Unfortunately, I upgraded to Windows 11, and apparently **win-vind** doesn't work well in it unfortunately. I hope to test the feature once Windows 11 gets supported. Meanwhile, I hope someone with the ability tests the feature. 

Thanks

**Comment by pit-ray** [comment]
I haven't tried Windows 11 yet. I'll do my best to support Windows 11 as soon as possible.
Thanks again for your feature suggestions.

**Comment by pit-ray** [comment]
I have confirmed that the installer and zip of win-vind 4.2.0-rc1 work on Windows 11 21H2 22000.168 Build, please check the log of your win-vind. If there are no errors, please describe the situation in more detail.

**Comment by Positron010** [comment]
Hi,
I am sorry, I just tried **win-vind** again, and it really does work. I really don't know why it didn't work when I tried it previously. I am going to try the feature. Sorry again for the mistake. Thanks for letting me know.

**Comment by pit-ray** [comment]
I'm glad it works. Thanks again!

**Comment by Positron010** [comment]
Just tried the feature, it works really well! Thanks, and good luck!
