### ISSUE TITLE
[Question] Easier Alt-Tab in Editor Modes

### ISSUE THREAD

**Issue by makeartandgames** [pit-ray/win-vind#39]
**Question**
I know that I can use [Ctrl+w > s] and [:ws] to alt-tab from GUI and command modes. However, how can I do this from Editor normal Mode? Right now I have to switch modes to do so.

**Comment by pit-ray** [comment]
Thanks for using it.

You can use **Command** mode from **Editor Normal** mode as well like `:sw` or `:switch`. In addition, `ennoremap` is available to define preferred bindings by writing .vindrc such as following.

```vim
ennoremap <C-w>s switch_window
```

Thanks.
