### ISSUE TITLE
How to use hinting like vimium?

### ISSUE THREAD

**Issue by therajat08** [pit-ray/win-vind#4]
cant figure out how to use hinting

**Comment by pit-ray** [comment]
Hi.  
In default, you can call the hinting feature with `F` (in key, `Shift` + `F`), which you can try after the first launch of win-vind.  

The default initial mode is called **GUI Normal**, which absorbs all inputs, but **GUI Insert** which does not. You can switch between <a href="https://pit-ray.github.io/win-vind/cheat_sheet/mode_ctrl/#change-to-normal">GUI Normal</a> and <a href="https://pit-ray.github.io/win-vind/cheat_sheet/mode_ctrl/#change-to-insert">GUI Insert</a> by pressing `ESC+Left` and `i` respectively.  

If you **only** want to use the hinting function, you can easily do it by following the steps.  

1. Open the key-config file, which locates **~/.win-vind/bindings.json** by installer or **config/bindings.json** by zip.  
1. Jump to line 1396. In Vim, you can jump to the line by `/easy_click` command.  
1. Rewrite the value of `guii`(**GUI Insert Mode**).  In the following example, we can call the feature with `Right Alt -> Right Ctrl`.  <br>  
   ```json
    {
        "name": "easy_click",
        "guin": ["F"],
        "guii": ["<ralt><rctrl>"],
        "guiv": [],
        "edin": [],
        "edii": [],
        "ediv": [],
        "edivl": [],
        "cmd": ["ec"],
        "en": "EasyClick",
        "jp": "EasyClick"
    },
   ```
   Please refer to <a href="https://pit-ray.github.io/win-vind/how_to_use/#key-config">How to Use/Customization/Key Config</a>.  
1. Input `:set` command, or right-click on the tray and select **Preference**.  
1. **Settings/Common/Initial Mode** -> **GUI Insert** and [   OK   ].

If you want more detailed information about **EasyClick**, please see the <a href="https://pit-ray.github.io/win-vind/cheat_sheet/mouse_ctrl/#easyclick">CheatSheet</a> or let me know.
