### ISSUE TITLE
[Bug] Overlay is not displayed on external monitor when laptop screen is off

### ISSUE THREAD

**Issue by hughwilliams94** [pit-ray/win-vind#45]
**Describe the bug**
I do not see any of the overlays for hints or the current mode or the command window. I think hinting is working as the cursor jumps around but the overlays visible in the GIF don't show up

**Environment (please complete the following information):**
- Windows 10 Edition: Enterprise
- OS Type: 64bit
- OS Version: 1909
- OS Build: 18363.19.16
- win-vind Version: 4.2.1
- win-vind Type: chocolatey
- Is it reproducible?: I only have access to one device, but the problem always occurs for me.

**Comment by pit-ray** [comment]
I will try to prepare the same environment and see if I can reproduce it. Please wait a moment.

Thanks.

**Comment by hughwilliams94** [comment]
It seems to be the fact that I am using an external monitor with my laptop screen shut. If I open the laptop so that both screens are active the overlay shows correctly, if the laptop screen is shut then the overlay does not appear. The `--Insert--` popup etc only shows on the laptop screen but the hints overlay appears on both.

**Comment by pit-ray** [comment]
It is the correct behavior that the virtual command line is only displayed on the primary monitor. If necessary, provide a way to show it on the extended monitor.

However, the fact that it does not show up on the closed laptop is most likely a bug. I will try on the same situation.

Thanks for the info.
