### ISSUE TITLE
[Question] How do you turn off control mouse with keyboard?

### ISSUE THREAD

**Issue by erikbye** [pit-ray/win-vind#46]
**Question**
Keybindings are good otherwise, but I don't want arrow keys to control the mouse cursor.

**Comment by pit-ray** [comment]
You can use the `unmap` command to remove bindings. (ref. https://pit-ray.github.io/win-vind/usage/#3-customize-win-vind)

For example, to disable the arrow key in GUI Normal mode (`gn`), write the following to .vindrc.

```vim
gnunmap <left>
gnunmap <right>
gnunmap <up>
gnunmap <down>
```

Thanks.
