### ISSUE TITLE
[Question] _How do I use the hinting system

### ISSUE THREAD

**Issue by rp1231** [pit-ray/win-vind#47]
Hi, 
I wanted to know how to use the hinting feature to navigate windows using the keyboard.
I can't figure out how to use this.....

Can someone help?

Thanks

**Comment by rp1231** [comment]
I enter the GUI normal mode as per the tutorial and start mspaint,
But I can't seem to bring up easy click by pressing FF.

**Comment by pit-ray** [comment]
`FF` is equal to `<shift-f><shift-f>`, is that correct?
If there is some errors, they will be outputed into `~/.win-vind/log/**.log`.

Thanks!

**Comment by rp1231** [comment]
Aah yes that works.

**Comment by godwinnnnn** [comment]
how to express when I want hit f key twice, which is all lowercase. such as `ff`. @pit-ray
