### ISSUE TITLE
[Question] is there vnoremap?

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#48]
Hi,

In order to quickly switch to normal and insert modes from visual mode, I have placed the following two lines in my `.vindrc`:
```
vnoremap <esc> to_edi_normal
vnoremap i to_insert
```

-- but I am getting an error: `E: not command (L:2)`

What am I doing wrong?

**Comment by pit-ray** [comment]
In win-vind, there are two each for Normal and Visual, so explicitly add `g` or `e` to the beginning.
(ref. https://pit-ray.github.io/win-vind/cheat_sheet/keywords/#mode-prefix)

|**Mode**|**noremap**|**map**|
|:---:|:---:|:---:|
|GUI Normal|`gnnoremap`|`gnmap`|
|GUI Visual|`gvnoremap`|`gvmap`|
|EDI Normal|`ennoremap`|`enmap`|
|EDI Visual|`evnoremap`|`evmap`|

Thanks.

**Comment by gilbh** [comment]
I see.

This makes good sense, but I am wondering if you should add a default `vnoremap` for those who assume it exists (though here a problem arises, since it might not default to the "right" mode assumed by the user. Perhaps you can make it "dynamic"? I.e., to default to the last active normal? Or is that too complicated? Just a thought).

**Comment by pit-ray** [comment]
Thanks for the idea.

It is useful to make `vnoremap` dynamic or to define `vnoremap` as an alias for `gvnoremap` and/or `evnoremap`, etc., but explicitly restricting it would be better for readability.

I'll leave it to pull requests for now.

Thanks.
