### ISSUE TITLE
[Question] How to reload .vindrc?

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#49]
Right now I simply close and re-open the app, but is there a way to reload `.vindrc`? Something like `:so %`?

**Comment by pit-ray** [comment]
You can reload .vindrc with `:source` or `:source ~/.win-vind/.vindrc`.
The former syntax reloads the same as the .vindrc loaded at startup. By the way, `:source` can be abbreviated as `:so`.

Thanks.

**Comment by gilbh** [comment]
Make sense!
