### ISSUE TITLE
Support for right-click and hover in EasyClick

### ISSUE THREAD

**Issue by tejasvi** [pit-ray/win-vind#5]
First off, great work!! There is no other implementation that comes this close to Vim emulation for Windows. You might want to enable [Github Sponsors](https://github.com/sponsors) to let people show their appreciation :)

It would be nice to be able to right click on the target using EasyClick, similar to left click. There could also be an additional *hover* motion which would only move the pointer without any click.

**Comment by pit-ray** [comment]
Thank you! I would like to enable GitHub Sponsors.

Your suggestion is nice. I would try to implement Left Click, Middle Click, Right Click, and Hovering in EasyClick. The idea right now is that these default bindings are going to be combined with the base key. (e.g. `Fa` is right click, `Fo` is left click, etc.)

**Comment by pit-ray** [comment]
I implemented four versions in EasyClick. You can try it at <a href="https://github.com/pit-ray/win-vind/releases/tag/v3.1.0">v3.1.0-beta</a>.
