### ISSUE TITLE
[Bug] The character '-' is invalid ascii key code in default_config/.vindrc

### ISSUE THREAD

**Issue by tudstlennkozh** [pit-ray/win-vind#53]
The 4.3.1 release is using a default config file in `default_config/.vindrc` and there's an error when launching the portable 64 bits release. The log says : 

> [Message] E: Invalid Syntax (L:277)
> 
> [Error] An runtime exception occurred from class std::vector<class vind::core::KeyCode,class std::allocator<class vind::core::KeyCode> > __cdecl vind::core::parse_pure_one_character_command(char). The character '-' is invalid ascii key code. (...\win-vind-4.3.1\default_config\.vindrc, L:277) (enum vind::SystemCall __cdecl vind::bind::SyscmdSource::sprocess(const class std::filesystem::path &,bool))
> 

The 4.2.1 has not this problem (`default_config/.vindrc` is inexistant in my config)

Please note that I was just launching win-vnid for a 1st use and my .vindrc (my own) is empty for the moment.

**Environment (please complete the following information):**
- Windows 10 Enterprise
- OS Type: 64bit
- OS Version: 21H1
- OS Build: 10.0.19043
- win-vind Version: 4.3.1
- win-vind Type: zip
- Is it reproducible?: Yes

**Comment by pit-ray** [comment]
Thanks for the detailed bug report.

This is an error in the process of determining whether or not shift is required when entering certain ascii codes.

I will try to reproduce it by preparing a similar environment.

**Comment by pit-ray** [comment]
I installed a new `Windows 10 Enterprise Evaluation 21H2 10.0.19044 64bit` and tried to run `win-vind 4.3.1 portable 64bit`. However, I was not able to reproduce the same issue.

Do you have any idea what might be causing the problem, such as a special keyboard layout?

I will continue to try to reproduce the problem.

**Comment by tudstlennkozh** [comment]
Hi,

thank you for your answer. I'm currently using a french keyboard layout (nothing specific with it). I tried on another computer (win10 home, 10.0.19044, 21H2) and I get the same error ... (exactly on the same line). I'm just starting to use win-vind and maybe, by just unzipping the portable release, I could have missed something ...?
Or, maybe, by first trying the 4.2.1 release and then the 4.3.1, there's a config file somewhere I did not see ... ?

**Comment by pit-ray** [comment]
Hi. Thanks for the quick answer.

I just tried the French keyboard layout on Windows and was able to reproduce the same problem!
I will implement the patch for the French keyboard layout as soon as possible.

By the way, Portable is completely independent, so there is no conflict.

**Comment by pit-ray** [comment]
Added support for the French keyboard layout and for entering accented characters in the virtual command line. However, accented characters in .vindrc are not yet supported.

The attached executable is a build of the above commit and has not been fully tested. I will release a stable version as 4.3.2 later, so please make sure to update it.

And, please let me know if it works.

Thanks!

[win-vind_c3f6177_64bit_portable.zip](https://github.com/pit-ray/win-vind/files/7798037/win-vind_c3f6177_64bit_portable.zip)

**Comment by tudstlennkozh** [comment]
Hi,
I confirm it's working without errors, congrats 👍 (I got a 1st error message regarding the impossibility to move cursor ... but was unable to reproduce)

**Comment by pit-ray** [comment]
That's good! Thanks for the great contribution!
