### ISSUE TITLE
[Bug] Easy click cannot work on scaled monitor

### ISSUE THREAD

**Issue by yuanotes** [pit-ray/win-vind#54]
Easy click shows wrong indicators on scaled monitors.

**Comment by pit-ray** [comment]
Do you mean Scale in Windows Settings > System > Display > Scale & layout? I tried it on my laptop scaled to 150% and had no problems.

Could you please tell me what version of Windows and win-vind you have so I can reproduce it?
Please use the following format. If you are using win-vind 4.3, you can find it in the log file.

> **Environment (please complete the following information):**
> - Windows 10 Edition: [e.g. Home, Pro, Enterprise].
> - OS Type: [64bit/32bit].
> - OS Version: [e.g. 1909, 20H2].
> - OS Build: [e.g. 19042.804].
> - win-vind Version: [e.g. 4.0.0].
> - Win-vind Type: [zip/installer].
> - Is it reproducible?: [Yes/No].

 Thanks.

**Comment by Meigs2** [comment]
I was having this issue, it probably has to do when you have multiple monitors with different scaling settings. I'm experiencing this issue with a Surface tablet screen at 3000x2000 set to 175% scaling in windows and two additional 1080p monitors set to 100% scaling.

To fix, try setting the DPI compatibility settings to "Advanced". Ideally you would be able to use "System (Enhanced)" which should do per-monitor scaling, but this does not seem to work as the locations of text when performing EasyClick are not correct on my high-res monitor.

Setting the fond drawing windows to use Per-Monitor V2 would be good, something like this? https://github.com/microsoft/Windows-classic-samples/blob/67a8cddc25880ebc64018e833f0bf51589fd4521/Samples/DPIAwarenessPerWindow/client/DpiAwarenessContext.cpp#L284

![image](https://user-images.githubusercontent.com/10554880/162070010-b46e7583-72c9-43c2-976c-6c9afd21b283.png)

**Comment by pit-ray** [comment]
@Meigs2 
Thanks for mentioning it.
I was able to reproduce it after changing the scale on multiple monitors as you describe. I will create a patch on your behalf using the fixes you suggested.

Thanks for your excellent contribution.

**Comment by Meigs2** [comment]
Of course. Great project, appreciate the support.
