### ISSUE TITLE
Highlighting not deleting

### ISSUE THREAD

**Issue by fredyonge** [pit-ray/win-vind#6]
Hey!
First of all: This looks amazing, thans a lot !

I have a few problems though:
(Win10)
When pressing "db" or "dw" it is highligting but not deleting

Also E doesn't work

Have a great day and thanks!
Greetings

**Comment by pit-ray** [comment]
I sincerely thank you for using it.  

`db` and `dw` seems to be working properly in my environment (Win10 64bit, notepad or Word). The behavior of Editor Mode depends on the editing capabilities of the target application, so please tell me what application you used.  

Also, please check `log/error.log` in a directory win-vind.exe is located **after the problem occurred**.  

As you can see <a href="https://pit-ray.github.io/win-vind/cheat_sheet/vim_emulation/#move-caret-words-forawrd">CheatSheet</a>, the `E` has not been implemented yet. Please count on the next version.

Thanks!
