### ISSUE TITLE
[Bug] can't run v4.3 installations

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#62]
I am having trouble running win-vind v4.3 on my laptop. It had a chocolatey installation of v4.2 (separate), but I am not sure if that is the reason. In any case, for both Installer and Portable 64bit, I am getting the following error trying to run the exe file:
![image](https://user-images.githubusercontent.com/39532610/148809377-95ac092b-5620-4047-aad6-734bce06a0d5.png)

**Comment by pit-ray** [comment]
I would like to reproduce it, so please let me know your environment shown in the issue template.

> **Environment (please complete the following information):**
> - Windows 10 Edition: [e.g. Home, Pro, Enterprise]
> - OS Type: [64bit/32bit]
> - OS Version: [e.g. 1909, 20H2]
> - OS Build: [e.g. 19042.804]
> - win-vind Version: [e.g. 4.0.0]
> - win-vind Type: [zip/installer]
> - Is it reproducible?: [Yes/No]

**Comment by gilbh** [comment]
Environment:
![image](https://user-images.githubusercontent.com/39532610/149012592-470d54cc-d22e-4214-88e2-d572e896f1e3.png)

win-vind Version: 4.3.2 (64-bit)
win-vind Type: both Installer and zip generate the same error
Reproducible: Yes, I am unable to run v. 4.3.2, it always generates this error and aborts.
