### ISSUE TITLE
[Question] instructions for using GUI NORMAL

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#63]
Hi

I wasn't able to locate instructions for keyboard operation in GUI NORMAL. I wanted to find which key operates right click, and was not able to locate that information.

I would like to know which key is right click, but also more importantly: where is such information kept on the website?

Thanks!

**Comment by pit-ray** [comment]
You can find it at [Cheat Sheet > Default mappings](https://pit-ray.github.io/win-vind/cheat_sheet/defaults/#mouse).

**Comment by gilbh** [comment]
Thanks!
