### ISSUE TITLE
[Bug] Two issues with blockstylecaret

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#64]
I am trying to use the blockstylecaret in order to be able to distinguish between EDIT NORMAL and INSERT. But I am encountering two problems:

1) I have the following setup in `.vindrc`:
```
set blockstylecaret
set blockstylecaret_mode = solid
set blockstylecaret_width = 10
```

-- the cursor looks as intended in EDIT NORMAL, but when I am working in Word and switch to INSERT, the caret does not change to a thin line (say 1 px width) but instead becomes half of the width I specified in `blockstylecaret_width`. I also noticed that if I changing the Zoom level changes the width: on a Zoom Out (say %300) the caret will look thin as it should, but the more I Zoom In, the wider the caret becomes (check, for example, %70 where it is really noticeable).

2) If I change `blockstylecaret` to `flex`, the caret looks weird on every movement, first white color and then semi-transparent. (But maybe that is something unavoidable because of Windows?).

Thanks for all the good work! I love working with win-vind.

**Comment by gilbh** [comment]
Environment:
![image](https://user-images.githubusercontent.com/39532610/149564235-3569bafb-36ed-4662-877d-21136cdfed4f.png)

win-vind Version: 4.3.2 (64-bit)
win-vind Type: both Installer and zip generate the same error
Reproducible: Yes, I am unable to run v. 4.3.2, it always generates this error and aborts.

**Comment by gilbh** [comment]
Here's my environment info:

Edition	Windows 10 Pro
Version	20H2
OS build	19042.1466
Experience	Windows Feature Experience Pack 120.2212.3920.0
System type	64-bit operating system, x64-based processor

win-vind: 4.3.2
win-vind type: installer
reproducible: yes

**Comment by pit-ray** [comment]
Rendering of the caret depends on that application and cannot be handled by win-vind.

I have tried to dynamically change the caret width with font and zoom, but have not been able to achieve it.
ref. https://github.com/pit-ray/win-vind/blob/master/src/opt/blockstylecaret.cpp#L49-L114

 `flex` only pseudo-reproduces it by temporarily selecting it, and it looks terrible.

Thanks.

**Comment by gilbh** [comment]
Thanks.

I am using `flex` now and it is working fine in terms of giving me a visual indication that I am in EDIT_NORMAL and not INSERT. When I move the caret it has a weird two-step look: first slim and then more thick, but that is okay. I don't think it is the end of the world.

Thanks again.
