### ISSUE TITLE
[Bug] `autofocus_textarea` slows down switching to EDIT NORMAL in Word

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#65]
If I set the following in `.vincrc`:
```
set autofocus_textarea = true
```
-- then the switch from INSERT to EDIT NORMAL in Word takes about a second, which is quite slow.

With thanks!!

**Comment by pit-ray** [comment]
I've been busy lately, so my reply has been slow.

`autofocus_textarea` scans the UI object every time, just like EasyClick, so there is a slight delay. To avoid it, it is recommended to enable `uiacachebuild` to do an asynchronous UI scan. However, v4.2 scans even in Insert mode, which is a bit uncomfortable behavior. (This has been resolved in 4.3).

ref. https://pit-ray.github.io/win-vind/cheat_sheet/options/

Also, please write the your environment for the bug report.

Thanks.

**Comment by gilbh** [comment]
Great. I will check out that option (on my v4.3 installation).

For bug report -- are you referring to  #64 ? I will do that now.

**Comment by pit-ray** [comment]
To reproduce each issue, it would be helpful if you could write an environment template or copy the header of the log file every time.

Thanks again.

**Comment by gilbh** [comment]
Will do. I have to run out of the house right now, but promise to get to this later today.

Again my thanks for your projects. I am now working more and more with it, switching from GUI NORMAL to EDIT NORMAL all the time!

**Comment by gilbh** [comment]
Here's my environment info:

Edition Windows 10 Pro
Version 20H2
OS build 19042.1466
Experience Windows Feature Experience Pack 120.2212.3920.0
System type 64-bit operating system, x64-based processor

win-vind: 4.3.2
win-vind type: installer
reproducible: yes
