### ISSUE TITLE
Bug: typo on website

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#66]
Webpage:
https://pit-ray.github.io/win-vind/usage/

Fix "Downlods":
![image](https://user-images.githubusercontent.com/39532610/151095439-699a3b2c-62d1-4e8a-abd1-8c9a7acbe7fd.png)

**Comment by pit-ray** [comment]
Sorry for the late replay, it's been a busy season lately.
If it's an obvious typo, you can use a pull request. For example, this time the page is `docs/usage/index.md`.

I'll fix it. Thanks.

**Comment by gilbh** [comment]
Thanks. Sorry, I never before did a pull request. Would be nice to try!
