### ISSUE TITLE
[Question] Can you diffrentiate between key press and key up?

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#70]
Hi,

I don't think this exists in vim, but can you distinguish between `key press` and `key up` in the key bindings that can be mapped in `.vinrc`?

If yes, then I would change my binding from:
```
inoremap <esc> to_edi_normal
```
to:
```
inoremap <esc[KEYUP]> to_edi_normal
```

-- that would go a long way toward ease of use of `win-vind`, because it will avoid incorrect actions and overlapping mappings, such as switching to other modes, like `<esc-up>` and so on. Only when the `<esc>` key press is released (=KEYUP) would it activate the binding....

**Comment by pit-ray** [comment]
It is possible to implement a distinction, but currently no such functionality is available.

If I only activate when release <kbd>ESC</kbd>, does that mean we have to press and hold it at all other times?

Sorry for the late reply.

**Comment by gilbh** [comment]
Some time has passed, so I am not sure now. It seems that my initial request wasn't clearly described: the logic for [KEY-UP] makes sense only if we have also the option of <esc-left> when the <esc> is KEY DOWN. This way, <esc> KEY-UP would work as general Escape key for all the apps, while the <esc-left> would work for win-vind without a conflict ... I hope this is clear. Let me know.

Best and keep up the great work!!
