### ISSUE TITLE
[Feature] display cmd on all screens

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#72]
Hi,

I am using two screens ("displays" in Windows language) on my Windows setup and it would be nice to see all the cmd's output on both of them and not just on screen 1, the reason being that sometime when I work on screen 2, I cannot be sure about the status of `win-vind` and need to look at the other screen, screen 1, to see the cmd feedback there (such as when I switched modes). 

So I think the right way is by default (or, alternatively, by a `.vindrc` command) to enable simultaneous display of the current cmd on both the screens (or more than two is set up that way).

Thank you!

**Comment by pit-ray** [comment]
That's true. It's essential to consider multiple displays. This will be implemented for sure.
