### ISSUE TITLE
[Bug] Microsoft Word delete row deletes the next char

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#77]
Hi,

In Microsoft Word, when I delete a whole row by pressing `dd` the first character of the next line is also deleted.

- Windows 10 Pro
- OS Type: 64bit
- OS Version: 21H2
- OS Build: 19044.1586
- win-vind Version: 4.4.0
- win-vind Type: zip
- Is it reproducible?: Yes

**Comment by pit-ray** [comment]
This is how it looks in my environment.

https://user-images.githubusercontent.com/42631247/158586821-b63b0321-4c5c-448b-9ce8-ad2c5814cc69.mp4

Maybe it is a MS Word version issue, so please also give me version information about MS Word.

**Comment by gilbh** [comment]
Thank you!

1) The `Use smart paragraph selection` seems unrelated. I tried with both options and the problem persists.
2) Your test is for two sentences that are shorter than one line. This helped me understand better the issue: it happens for **one sentence that is longer than one line**. Can you please try that and let me know if you can now reproduce?
3) MS Word version:
![image](https://user-images.githubusercontent.com/39532610/158603973-8cd3c35d-1e26-4839-85fe-ef503ced60a7.png)

**Comment by pit-ray** [comment]
I was able to reproduce it. This is a bug of win-vind.

**one-line** you said means too long sentence is drawn on the next line without including the newline code. In other words, it is a case of `set wrap` in Vim.

like this.
![image](https://user-images.githubusercontent.com/42631247/160071263-1ac944d9-496e-4b57-a92c-903132924a45.png)


In this case, do you think it is better to select up to the true newline code as in `wrap` or to consider the unit being drawn as one line?

- true one-line
  ![image](https://user-images.githubusercontent.com/42631247/160071530-73474e07-5cc7-429c-85a7-a66d56cdf5fd.png)

- drawn one-line
  ![image](https://user-images.githubusercontent.com/42631247/160071486-5e784eaf-47e5-4cab-bb7b-6147acdb43cf.png)


Thanks for beta testing!

**Comment by gilbh** [comment]
Working in Word, I can definitely say it should be one line and not the true one-line.
