### ISSUE TITLE
[Bug] yank crashes in Word (when inside footnote)

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#79]
When I try to yank a complete footnote (typing`y$`) win-vind crashes.

    Windows 10 Pro
    OS Type: 64bit
    OS Version: 21H2
    OS Build: 19044.1586
    win-vind Version: 4.4.0
    win-vind Type: zip
    Is it reproducible?: Yes

**Comment by pit-ray** [comment]
Thanks for the report.
This is definitely a bug. I'll fix in 4.4.0-beta2.

**Comment by pit-ray** [comment]
This issue has already been solved.
