### ISSUE TITLE
Cannot create setting files after install

### ISSUE THREAD

**Issue by insanerwayner** [pit-ray/win-vind#8]
After first install and first launch getting this error:

```
An runtime exception occurred from void __cdecl Utility::create_directory(const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &). Cannot create a directory \\.win-vind\.. So could not create setting files of win-vind, so terminate. (Windows Error Code: 161)
```

Tried running as administrator and still getting the same error.

## System Info

|            |                                             |
|--------|-------------------------------|
|Edition| Windows 10 Enterprise LTSC|
|Version| 1809 |
|OS build| 17763.1757|

**Comment by pit-ray** [comment]
Thank you for the bug report.

v3.2.0 has some problem in a filesystem, so patched as v3.2.1. Did you try [v3.2.1](https://github.com/pit-ray/win-vind/releases/tag/v3.2.1)?

If you received an error with v3.2.1, this is an undiscovered bug. In this case, please let me know the included languages in a full path to your user directory. And please test zip-version. I will prepare the same environment and test for fixing.

**Comment by insanerwayner** [comment]
This is with version **3.2.1**

Full path to home `C:\Users\wreeves`

I uninstalled it and reinstalled using the zip version and it had the same results.

**Comment by pit-ray** [comment]
Thanks. I'm testing now.

**Comment by pit-ray** [comment]
I tested with **Windows 10 Enterprise LTSC Evaluation 64bit (Build 17763.rs5_release.180914-1434)** but couldn't reproduce it. 

The error shown at the beginning states that the path is invalid. In other words, it failed to get the home directory (environment variable **%HOMEPATH%**). so changed the way to get the home path.

Please try [v3.2.2-preview](https://github.com/pit-ray/win-vind/releases/tag/v3.2.2).

The zip version is designed to be installed into a **non**-administrator directory, so configuration files are generated in the same directory as `win-vind.exe`.

I hope it works.

**Comment by insanerwayner** [comment]
That worked!
