### ISSUE TITLE
[Feature] Radical suggest: f/HopWord on apps

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#80]
I started using `vimium-c` add-on for web browsers, which has this fantastic feature `f`: it immediately highlights all clickable areas on the page with keyboard shortcuts. It makes any click operation immediate and easy:
![image](https://user-images.githubusercontent.com/39532610/160260623-8b0842a8-dfe5-4644-9508-26d0d20f5632.png)

Another implementation for the same concept is `hop.nvim`'s `:HopWord` with does a similar thing inside nvim:
![image](https://user-images.githubusercontent.com/39532610/160260699-02515cec-4ac3-4031-a521-28f2597f818e.png)

I am doubtful Windows lets you do this, but if you are able to "sense" and highlight all the **clickable** areas of the activated application, and then assign random keyboard shortcuts to them, it would be magic. A sort of separate mode in addition to EDIT and GUI. 

Let me know your thoughts,
Best
Gil

**Describe the feature you'd like**

**Related projects (Optional)**
The existing projects with a similar feature that you can think of.

**Comment by pit-ray** [comment]
What makes this different from EasyClick? EasyClick detects all clickable UI and assigns a hint to each one.

**Comment by gilbh** [comment]
I was not aware of EasyClick. I will start testing it. Can you please make the labels' background color yellow and the font to Bold? It would be easier to see the letter on a wide screen.

Thanks!!

**Comment by gilbh** [comment]
Here is an example of how Vimium-C colors the labels:

**Comment by pit-ray** [comment]
As shown here, various versions of EasyClick are available.
https://pit-ray.github.io/win-vind/cheat_sheet/functions/#mouse

By default, it can be started with `FF` in GUI mode. These EasyClick are also available in Editor mode by assigning it.
https://pit-ray.github.io/win-vind/cheat_sheet/defaults/#mouse

To change the color, font, size, or weight, there are a lot of parameter named `easyclick_*.` 
https://pit-ray.github.io/win-vind/cheat_sheet/options/

The following example is changing to the style you indicated. Colors should be adjusted a little more.
```vim
set easyclick_bgcolor=#cb9925
set easyclick_fontcolor=#000000
set easyclick_fontweight=800
set easyclick_fontsize=17
set easyclick_fontname=Arial
```

**Comment by gilbh** [comment]
Incredible! I will implement this right away. Thanks!
