### ISSUE TITLE
[Feature] optional: current mode label should stick and not disappear

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#82]
Hi,

At times I find myself at lost as to what is the current mode I am in. (The caret does not indicate with in GUI, and it is also changes it shape in Word, so that is not a solution).

We already discussed the idea of having mode-based icons as indicators, but I just now thought of another, easy solution: can you make the mode label "stick" on the screen? This should probably be optional, as many would prefer the label to go away after a second or two, but having used vimium-c for some time now, I realize just how helpful it is to know the current mode, especially after some time has passed since you switched to it.

(I realize this might clash with the "regular" output prompt, but I do hope you consider this option).

Thanks and keep up the great work!

**Comment by pit-ray** [comment]
Is it not possible to use set `set cmd_fadeout=3600`?

**Comment by gilbh** [comment]
Yes, that works! Thanks.
