### ISSUE TITLE
[Question] Shift to INSERT after EasyClick operation

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#84]
Hi,

Is there a switch for jumping automatically to INSERT after an EasyClick button is clicked? This would b immensely helpful, as many times I need to continue the operation chosen by the EasyClick.

If there is no such switch, please consider adding. I think it would be very useful to many.

Thanks
Gil

**Comment by pit-ray** [comment]
You can do EasyClick after entering insert mode.

```vim
inoremap <f20> easy_click_left
gnnoremap <ctrl-1> i<f20>
```

Thanks.

**Comment by gilbh** [comment]
Thanks!!
