### ISSUE TITLE
[Bug] `<c-f>` behaves like `f` in NORMAL

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#86]
Hi, 

I am using this mapping setup:
```
inoremap <f20> easy_click_left
ennoremap f i<f20>
```

Now every time I type `<c-f>` to scroll down, I get EasyClick. It appears that the `f` mapping catches also the `<ctrl>`.

Thanks for responding!

**Comment by pit-ray** [comment]
Simple commands encompass more complex commands.
This issue is fundamentally the same as #83.
Thanks.
