### ISSUE TITLE
[Question] Weird behavior in NORMAL after `<c-k>`?

### ISSUE THREAD

**Issue by gilbh** [pit-ray/win-vind#87]
Hi,

I added this:
```
inoremap <c-k> to_edi_normal
```

-- but oddly when I type this the movement of the caret now highlights whole words. Also, all the `<c-` mappings are behaving strange, like `<c-e>` stops scrolling etc.

Please check and advise what I am doing wrong?

Thanks!!

This happens to me in Microsoft Word.

**Comment by pit-ray** [comment]
It seems to me that `<c-k>` in MS Word conflicts with shortcuts.
Also, what version of win-vind do you have?
Thanks.

**Comment by gilbh** [comment]
The About shows version 4.3.3, but I am using the beta version you offered me for testing `e` ... I can't verify this because I think the About version is not updated ...

I checked and `<c-k>` without running win-vind does nothing in my Word. When I run it with win-vind, it does switch to Edit Normal, but with auto highlighting of every word I move the cursor to.

Hope this helps...

Thanks
Gil

**Comment by pit-ray** [comment]
Do you mean the highlighting that is selected and turns blue?
A screenshot image would be helpful.

I have not been able to reproduce it, so please try the portable version with just `inoremap <c-k> to_edi_normal`.
And if you know the smallest reproducible .vindrc, please let me know.

I will be able to develop win-vind this month.
Thanks again.

**Comment by gilbh** [comment]
Screenshot:
![image](https://user-images.githubusercontent.com/39532610/172908219-5e49f950-12b3-4268-a6cc-fb77eced0ca2.png)
Here, you can see the word "Gracefully" highlighted. If I click `l`, the highlight will jump to "blazing"....
 
I just tried to official release portable, adding to the empty `.vindrc` the mapping line from above, and it worked fine: `<c-k>` switched to Edit Normal without going into this weird auto-highlighting mode ... I guess this shows that the issue is related to the new `e` mechanism you added to the beta? This makes sense to me somehow, since `e` actually highlights the word in order to find its end, correct?

**Comment by gilbh** [comment]
Sure. Just a thought: perhaps it is the issue described in #83 and #86 ?

**Comment by pit-ray** [comment]
This problem has been fixed in v5.
