### ISSUE TITLE
[Bug] Partial mapping does not work.

### ISSUE THREAD

**Issue by pit-ray** [pit-ray/win-vind#93]
### Discussed in https://github.com/pit-ray/win-vind/discussions/88

> <div type='discussions-op-text'>
> 
> <sup>Originally posted by **akhasano** April 22, 2022</sup>
> Hello,
> It is not working for me https://pit-ray.github.io/win-vind/faq/
> 
> I would change ESC to any other button (ideally LCtrl+Win instead ESC) but it doesn't work. 
> Does it should work in any Windows? I have Windows 10 Pro 21H2 and it doesn't work.
> What I am do, I am using portable version unpacked to "D:\soft\win-vind":
> * Run as regular user
> * From tray - open root directory
> * Open .vindrc and put text from page: https://pit-ray.github.io/win-vind/faq/
> 
> switch to gui normal, ":e source", trying to restart app.
> Expectation: <caps>+left or right or down works as <esc>+left or right or down. But it still works with "esc" and ignores "caps".
> If i put "set cmd_fontname = Times New Roman" and restart - I can see font is changed from Verdana to TNR.
> Version: 4.3.3
> 
> Can you please advice? 
> Thanks.</div>

The partial mapping as in the FAQ does not seem to work.

**Comment by imshenwei** [comment]
gnmapclear
gvmapclear
enmapclear
evmapclear
imapclear
rmapclear
cmapclear

gnnoremap : to_command
gnnoremap :s :source
gnnoremap i to_insert
gnnoremap <esc-down> to_resident
gnnoremap <c-shift> to_resident
inoremap <esc-down> to_resident 
inoremap <c-shift> to_gui_normal
rnoremap <c-shift> to_gui_normal
rnoremap <esc-left> to_gui_normal
gnnoremap q click_left
gnnoremap e click_right
gnnoremap w move_cursor_up
gnnoremap s move_cursor_down
gnnoremap a move_cursor_left
gnnoremap d move_cursor_right
gnnoremap r scroll_up_halfpage
gnnoremap f scroll_down_halfpage
gnnoremap <a-w> scroll_up
gnnoremap <a-s> scroll_down
gnnoremap <a-a> scroll_left
gnnoremap <a-d> scroll_right
gnnoremap t easy_click_left
gnnoremap g easy_click_right
gnnoremap <s-q> easy_click_hover
gnnoremap <s-e> easy_click_mid
gnnoremap <c-f> search_pattern
gnnoremap <c-y> redo
gnnoremap <c-tab> goto_next_page
gnnoremap <c-s-tab> goto_prev_page
gnnoremap <win> open_startmenu
gnnoremap <c-a> select_all
gnnoremap <bs> hotkey_backspace
gnnoremap <c-x> hotkey_cut
gnnoremap <c-v> hotkey_paste
gnnoremap <c-z> undo
gnnoremap <del> hotkey_delete
gnnoremap <c-c> hotkey_copy
gnnoremap <c-v-left> switch_to_left_vdesktop
gnnoremap <c-v-right> switch_to_right_vdesktop
gnnoremap <c-win-d> create_new_vdesktop
gnnoremap <c-win-f4> close_current_vdesktop
gnnoremap <a-tab> taskview
