### ISSUE TITLE
[Question] issue with the jump_cursor_with_keybrd_layout function

### ISSUE THREAD

**Issue by petertheprocess** [pit-ray/win-vind#99]
Hello, I just learned about and use this project recently. It is awesome, and my favorite function is the jump_cursor_with_keybrd_layout, by which I can say goodbye to my mouse.
However, I find that when more than one monitor are connected, this jump function seems to work weirdly. When I type <f-f>, the cursor jump to the mid-bottom, the red position in the pic, in my no.1 monitor.
![image](https://user-images.githubusercontent.com/30321432/174031282-8e92e824-cf00-4211-ac71-940c173face5.png)
And the cursor never jumps to my no.2 monitor by the <f-another key>. I think the best effect is to detect the screen where the cursor is located, and then perform this jump only with the detected monitor.

![image](https://user-images.githubusercontent.com/30321432/174028551-15abf5bf-15a4-40f9-bae2-130b7bad3111.png)
(this is my monitor layout)

In addition, I am using a 61-key layout keyboard, is it possible to use this function within the alphabet area? How should I set it？

**Comment by pit-ray** [comment]
I created patch for keyboard projection on the monitor where the cursor is located.
I will add it officially in v4.4.0, but if you want to use it as a beta version, you can build it by installing MSVC and NSIS and running the following.
```sh
$ . /tools/setup_libs.bat issue99 -msvc 64
$ . /tools/create_assets.bat issue99 -msvc 64
````

If you want to use it for your preferred keyboard layout, write `custom.kmp` file in the config directory and link the screen coordinates to the key codes. The coordinates are normalized by the maximum value of x and y, respectively.
```
set keybrd_layout=custom.kmp
````
ref. https://github.com/pit-ray/win-vind/blob/2d7c1cda120eef31083ba689e94e855eb31f9bf3/res/default_config/US.kmp

If it is a general keyboard layout for your language, you can share the created `.kmp` file for other people. If then, add the `.kmp` file into `res/default_config` and register it like [this](
https://github.com/pit-ray/win-vind/blob/2d7c1cda120eef31083ba689e94e855eb31f9bf3/src/core/keylayout.cpp), and please send pull request.

Thanks for using it.

**Comment by petertheprocess** [comment]
Thanks a lot, I will try it when I am avalible.
